import { Difficulty } from "../types";

interface PresetCategory {
  name: string;
  words: {
    [key in Difficulty]: string[];
  };
}

interface UndercoverCategory {
  name: string;
  pairs: {
    [key in Difficulty]: [string, string][];
  };
}

const PRESETS: PresetCategory[] = [
  {
    name: "Animals",
    words: {
      EASY: ["Dog", "Cat", "Elephant", "Lion", "Tiger", "Bear", "Giraffe", "Monkey", "Cow", "Pig", "Horse", "Sheep", "Duck", "Chicken", "Rabbit", "Mouse", "Frog", "Snake", "Fish", "Whale", "Dolphin", "Shark", "Wolf", "Fox", "Deer", "Hamster", "Goldfish", "Turtle", "Parrot", "Goat", "Donkey", "Pony", "Rat", "Bat", "Squirrel", "Chipmunk", "Raccoon", "Skunk", "Beaver", "Otter", "Seal", "Penguin", "Panda", "Koala", "Kangaroo", "Zebra", "Hippo", "Rhino", "Gorilla", "Chimp"],
      MEDIUM: ["Kangaroo", "Penguin", "Octopus", "Rhinoceros", "Hippopotamus", "Koala", "Platypus", "Ostrich", "Camel", "Zebra", "Gorilla", "Chimpanzee", "Panda", "Leopard", "Cheetah", "Jaguar", "Bison", "Moose", "Beaver", "Otter", "Seal", "Walrus", "Owl", "Eagle", "Parrot", "Llama", "Alpaca", "Antelope", "Gazelle", "Baboon", "Orangutan", "Lemur", "Sloth", "Badger", "Mole", "Hedgehog", "Porcupine", "Armadillo", "Anteater", "Aardvark", "Meerkat", "Hyena", "Jackal", "Coyote", "Dingo", "Lynx", "Bobcat", "Puma", "Elk", "Reindeer"],
      HARD: ["Axolotl", "Narwhal", "Pangolin", "Capybara", "Tapir", "Okapi", "Cassowary", "Echidna", "Wombat", "Lemur", "Meerkat", "Aardvark", "Armadillo", "Sloth", "Anteater", "Porcupine", "Badger", "Weasel", "Mongoose", "Hyena", "Jackal", "Coyote", "Dingo", "Lynx", "Bobcat", "Fennec Fox", "Serval", "Caracal", "Ocelot", "Margay", "Civet", "Genet", "Binturong", "Fossa", "Kinkajou", "Coati", "Tamarin", "Marmoset", "Howler Monkey", "Gibbon", "Siamang", "Mandrill", "Drill", "Colobus", "Langur", "Macaque", "Vervet", "Tarsier", "Galago", "Loris"],
      INSANE: ["Quokka", "Fossa", "Aye-aye", "Dugong", "Vaquita", "Saola", "Kakapo", "Tuatara", "Tarsier", "Slow Loris", "Manatee", "Nautilus", "Cuttlefish", "Nudibranch", "Mantis Shrimp", "Tardigrade", "Coelacanth", "Goblin Shark", "Blobfish", "Jerboa", "Civet", "Binturong", "Solenodon", "Tenrec", "Desman", "Colugo", "Tree Shrew", "Hyrax", "Agouti", "Paca", "Mara", "Viscacha", "Chinchilla", "Degu", "Hutia", "Coypu", "Gundi", "Laotian Rock Rat", "Marsupial Mole", "Numbat", "Quoll", "Dunnart", "Planigale", "Mulgara", "Kowari", "Dibbler", "Phascogale"]
    }
  },
  {
    name: "Food",
    words: {
      EASY: ["Pizza", "Burger", "Apple", "Banana", "Ice Cream", "Pasta", "Bread", "Cheese", "Egg", "Milk", "Cake", "Cookie", "Donut", "Fries", "Hot Dog", "Sandwich", "Soup", "Salad", "Rice", "Steak", "Chicken", "Fish", "Chocolate", "Candy", "Popcorn", "Toast", "Cereal", "Pancake", "Waffle", "Yogurt", "Butter", "Jam", "Honey", "Chip", "Cracker", "Pretzel", "Nut", "Fruit", "Vegetable", "Meat", "Bacon", "Ham", "Sausage", "Beef", "Pork", "Lamb", "Pie", "Tart", "Muffin", "Bagel"],
      MEDIUM: ["Sushi", "Tacos", "Lasagna", "Croissant", "Burrito", "Dumplings", "Curry", "Pancakes", "Waffles", "Omelette", "Yogurt", "Smoothie", "Bagel", "Muffin", "Brownie", "Cupcake", "Pie", "Pudding", "Jelly", "Jam", "Honey", "Butter", "Cream", "Sauce", "Spice", "Ramen", "Noodle", "Stir-fry", "Kebab", "Falafel", "Hummus", "Pita", "Naan", "Samosa", "Spring Roll", "Dim Sum", "Tempura", "Sashimi", "Miso", "Tofu", "Kimchi", "Bibimbap", "Bulgogi", "Pad Thai", "Satay", "Laksa", "Pho", "Banh Mi", "Gyoza", "Bao"],
      HARD: ["Ratatouille", "Paella", "Baklava", "Gnocchi", "Escargot", "Kimchi", "Hummus", "Falafel", "Shawarma", "Kebab", "Gyro", "Tapas", "Fondue", "Raclette", "Bruschetta", "Focaccia", "Ciabatta", "Sourdough", "Baguette", "Pretzel", "Strudel", "Cannoli", "Tiramisu", "Gelato", "Sorbet", "Ceviche", "Carpaccio", "Tartare", "Confit", "Cassoulet", "Bouillabaisse", "Coq au Vin", "Beef Wellington", "Lobster Thermidor", "Oysters Rockefeller", "Eggs Benedict", "Vichyssoise", "Gazpacho", "Borscht", "Goulash", "Schnitzel", "Sauerbraten", "Spaetzle", "Pierogi", "Blini", "Caviar", "Foie Gras", "Truffle", "Saffron", "Vanilla"],
      INSANE: ["Haggis", "Surströmming", "Balut", "Natto", "Durian", "Lutefisk", "Century Egg", "Bird's Nest Soup", "Fugu", "Hakarl", "Casu Marzu", "Rocky Mountain Oysters", "Head Cheese", "Black Pudding", "Scrapple", "Spam", "Vegemite", "Marmite", "Bovril", "Kopi Luwak", "Truffle", "Saffron", "Caviar", "Foie Gras", "Ortolan", "Shirako", "Escamoles", "Huitlacoche", "Cuy", "Muktuk", "Kiviak", "Sannakji", "Beondegi", "Shiokara", "Tuna Eyeball", "Wasp Crackers", "Fried Spider", "Silkworm Pupae", "Grasshopper", "Cricket", "Scorpion", "Snake Wine", "Bear Paw", "Moose Nose", "Jellied Moose Nose", "Stargazey Pie", "Spotted Dick", "Eton Mess"]
    }
  },
  {
    name: "Jobs",
    words: {
      EASY: ["Doctor", "Teacher", "Police", "Chef", "Firefighter", "Artist", "Farmer", "Nurse", "Pilot", "Driver", "Singer", "Actor", "Dancer", "Writer", "Soldier", "Judge", "Lawyer", "Baker", "Butcher", "Waiter", "Maid", "Guard", "Coach", "Clerk", "Guide", "Dentist", "Vet", "Mechanic", "Plumber", "Electrician", "Carpenter", "Painter", "Cleaner", "Cook", "Server", "Host", "Cashier", "Manager", "Boss", "Worker", "Builder", "Sailor", "Miner", "Fisher", "Hunter", "Priest", "Nun", "Monk", "King", "Queen"],
      MEDIUM: ["Architect", "Scientist", "Journalist", "Plumber", "Electrician", "Dentist", "Surgeon", "Vet", "Mechanic", "Carpenter", "Painter", "Welder", "Miner", "Fisher", "Hunter", "Barber", "Tailor", "Banker", "Broker", "Agent", "Manager", "Director", "Editor", "Author", "Poet", "Engineer", "Developer", "Designer", "Consultant", "Analyst", "Accountant", "Auditor", "Marketer", "Recruiter", "Trainer", "Therapist", "Counselor", "Pharmacist", "Optometrist", "Chiropractor", "Paramedic", "Midwife", "Librarian", "Curator", "Archivist", "Translator", "Interpreter", "Diplomat", "Politician", "Judge"],
      HARD: ["Actuary", "Paleontologist", "Epidemiologist", "Cartographer", "Sommelier", "Astronomer", "Geologist", "Biologist", "Chemist", "Physicist", "Mathematician", "Statistician", "Economist", "Historian", "Linguist", "Philosopher", "Psychologist", "Sociologist", "Anthropologist", "Archaeologist", "Curator", "Librarian", "Archivist", "Diplomat", "Politician", "Meteorologist", "Oceanographer", "Seismologist", "Volcanologist", "Hydrologist", "Ecologist", "Geneticist", "Microbiologist", "Virologist", "Immunologist", "Neurologist", "Cardiologist", "Oncologist", "Dermatologist", "Pediatrician", "Geriatrician", "Psychiatrist", "Anesthesiologist", "Radiologist", "Pathologist", "Forensic Scientist", "Toxicologist", "Criminologist", "Ballistician"],
      INSANE: ["Numismatist", "Apiarist", "Horologist", "Vexillologist", "Speleologist", "Taxidermist", "Cooper", "Cobbler", "Farrier", "Fletcher", "Chandler", "Milliner", "Haberdasher", "Draper", "Mercer", "Scrivener", "Tanner", "Fuller", "Dyer", "Weaver", "Spinner", "Carder", "Shearer", "Thatcher", "Mason", "Wheelwright", "Wainwright", "Shipwright", "Cartwright", "Arkwright", "Ploughwright", "Sievewright", "Bridle Cutter", "Saddler", "Currier", "Cordwainer", "Loriner", "Glover", "Hatter", "Hosier", "Tailor", "Seamstress", "Mantua Maker", "Modiste", "Lapidary", "Goldsmith", "Silversmith", "Blacksmith", "Whitesmith", "Locksmith"]
    }
  },
  {
    name: "Countries",
    words: {
      EASY: ["USA", "China", "India", "France", "Italy", "Japan", "Brazil", "Canada", "UK", "Germany", "Russia", "Spain", "Mexico", "Egypt", "Australia", "Turkey", "Korea", "Iran", "Iraq", "Saudi Arabia", "South Africa", "Argentina", "Colombia", "Peru", "Chile", "Vietnam", "Thailand", "Indonesia", "Malaysia", "Philippines", "Singapore", "New Zealand", "Fiji", "Samoa", "Tonga", "Pakistan", "Afghanistan", "Bangladesh", "Nepal", "Sri Lanka", "Maldives", "Israel", "Jordan", "Syria", "Lebanon", "Yemen", "Oman", "UAE", "Qatar", "Kuwait"],
      MEDIUM: ["Thailand", "Greece", "Sweden", "Norway", "Finland", "Denmark", "Poland", "Ukraine", "Romania", "Hungary", "Austria", "Swiss", "Belgium", "Netherlands", "Ireland", "Portugal", "Morocco", "Vietnam", "Malaysia", "Indonesia", "Philippines", "New Zealand", "Pakistan", "Israel", "Kenya", "Czechia", "Slovakia", "Slovenia", "Croatia", "Bosnia", "Serbia", "Montenegro", "Albania", "Macedonia", "Bulgaria", "Moldova", "Belarus", "Lithuania", "Latvia", "Estonia", "Iceland", "Malta", "Cyprus", "Georgia", "Armenia", "Azerbaijan", "Kazakhstan", "Uzbekistan", "Turkmenistan", "Kyrgyzstan", "Tajikistan"],
      HARD: ["Nigeria", "Ghana", "Ethiopia", "Somalia", "Sudan", "Libya", "Tunisia", "Algeria", "Mali", "Chad", "Niger", "Senegal", "Guinea", "Liberia", "Ivory Coast", "Cameroon", "Gabon", "Congo", "Angola", "Zambia", "Zimbabwe", "Botswana", "Namibia", "Mozambique", "Madagascar", "Tanzania", "Uganda", "Rwanda", "Burundi", "Malawi", "Lesotho", "Swaziland", "Mauritius", "Seychelles", "Comoros", "Eritrea", "Djibouti", "South Sudan", "Central African Republic", "Equatorial Guinea", "Sao Tome", "Cape Verde", "Gambia", "Guinea-Bissau", "Sierra Leone", "Burkina Faso", "Togo", "Benin", "Mauritania", "Western Sahara"],
      INSANE: ["Kyrgyzstan", "Liechtenstein", "Djibouti", "Tuvalu", "Nauru", "Bhutan", "Andorra", "San Marino", "Monaco", "Vatican", "Malta", "Cyprus", "Bahrain", "Qatar", "Kuwait", "Oman", "Yemen", "Syria", "Lebanon", "Jordan", "Palestine", "Armenia", "Georgia", "Azerbaijan", "Kazakhstan", "Marshall Islands", "Micronesia", "Palau", "Kiribati", "Solomon Islands", "Vanuatu", "Timor-Leste", "Brunei", "Barbados", "Saint Lucia", "Grenada", "Dominica", "Antigua", "Saint Kitts", "Saint Vincent", "Trinidad", "Bahamas", "Belize", "Suriname", "Guyana", "French Guiana", "Falkland Islands", "Gibraltar", "Faroe Islands", "Greenland", "Svalbard"]
    }
  },
  {
    name: "Star Wars",
    words: {
      EASY: ["Luke", "Leia", "Han Solo", "Chewbacca", "Vader", "Yoda", "R2-D2", "C-3PO", "Obi-Wan", "Anakin", "Padme", "Rey", "Finn", "Poe", "Kylo Ren", "BB-8", "Mandalorian", "Baby Yoda", "Grogu", "Boba Fett", "Jabba", "Emperor", "Maul", "Stormtrooper", "Droid", "Jedi", "Sith", "Force", "Lightsaber", "Blaster"],
      MEDIUM: ["Ahsoka", "Rex", "Cody", "Windu", "Qui-Gon", "Grievous", "Dooku", "Ventress", "Thrawn", "Ezra", "Sabine", "Hera", "Kanan", "Zeb", "Chopper", "Cal Kestis", "Bo-Katan", "Cad Bane", "Hondo", "Tarkin", "Mothma", "Andor", "Jyn Erso", "K-2SO", "Lando", "Ackbar", "Wicket", "Jar Jar", "Sebulba", "Watto"],
      HARD: ["Revan", "Malak", "Bastila", "Nihilus", "Sion", "Traya", "Bane", "Zannah", "Plagueis", "Sidious", "Tyranus", "Valkorion", "Arcann", "Vaylin", "Satele", "Marr", "Jace", "Theron", "Lana", "HK-47", "T3-M4", "Canderous", "Carth", "Mission", "Zaalbar", "Jolee", "Juhani", "Visas", "Handmaiden", "Disciple"],
      INSANE: ["Exar Kun", "Ulic", "Nomi", "Cay", "Tott", "Vodo", "Arca", "Thon", "Odan-Urr", "Naga Sadow", "Ludo Kressh", "Marka Ragnos", "Ajunta Pall", "Tulak Hord", "Freedon Nadd", "Ommin", "Amanoa", "Novar", "Warb Null", "Aleema", "Satal", "Crado", "Oss Wilum", "Dace Diath", "Shoaneb", "Qrrrl", "Sylvar", "Dominic", "Gora", "Bodo Baas"]
    }
  },
  {
    name: "Harry Potter",
    words: {
      EASY: ["Harry", "Ron", "Hermione", "Dumbledore", "Snape", "Voldemort", "Hagrid", "Draco", "Sirius", "Lupin", "Dobby", "McGonagall", "Ginny", "Fred", "George", "Neville", "Luna", "Bellatrix", "Lucius", "Narcissa", "Hedwig", "Fang", "Crookshanks", "Scabbers", "Trevor", "Fawkes", "Buckbeak", "Aragog", "Fluffy", "Norbert"],
      MEDIUM: ["Moody", "Tonks", "Kingsley", "Shacklebolt", "Slughorn", "Sprout", "Flitwick", "Trelawney", "Quirrell", "Lockhart", "Umbridge", "Fudge", "Scrimgeour", "Thicknesse", "Crouch", "Bagman", "Karkaroff", "Maxime", "Delacour", "Krum", "Diggory", "Chang", "Patil", "Brown", "Thomas", "Finnigan", "Longbottom", "Lovegood", "Weasley", "Potter"],
      HARD: ["Peverell", "Gaunt", "Riddle", "Black", "Lestrange", "Malfoy", "Rosier", "Travers", "Mulciber", "Dolohov", "Rookwood", "Yaxley", "Greyback", "Pettigrew", "Quirrell", "Barty", "Regulus", "Andromeda", "Ted", "Nymphadora", "Remus", "James", "Lily", "Peter", "Sirius", "Severus", "Albus", "Aberforth", "Ariana", "Gellert"],
      INSANE: ["Wulfric", "Brian", "Percival", "Kendra", "Honoria", "Merope", "Morfin", "Marvolo", "Tom", "Eileen", "Tobias", "Septimus", "Cedrella", "Phineas", "Nigellus", "Ursula", "Armando", "Dilys", "Dexter", "Everard", "Phyllida", "Spore", "Newt", "Theseus", "Leta", "Tina", "Queenie", "Jacob", "Credence", "Nagini"]
    }
  },
  {
    name: "Marvel",
    words: {
      EASY: ["Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye", "Spider-Man", "Wolverine", "Deadpool", "Thanos", "Loki", "Ultron", "Venom", "Green Goblin", "Doctor Octopus", "Magneto", "Mystique", "Cyclops", "Jean Grey", "Storm", "Rogue", "Gambit", "Beast", "Professor X", "Ant-Man", "Wasp", "Black Panther", "Doctor Strange", "Scarlet Witch", "Vision"],
      MEDIUM: ["Star-Lord", "Gamora", "Drax", "Rocket", "Groot", "Nebula", "Mantis", "Falcon", "Winter Soldier", "War Machine", "Pepper Potts", "Happy Hogan", "Nick Fury", "Maria Hill", "Coulson", "Peggy Carter", "Sharon Carter", "Zemo", "Red Skull", "Hela", "Surtur", "Dormammu", "Ego", "Killmonger", "Shuri", "Okoye", "Nakia", "M'Baku", "Wong", "Ancient One"],
      HARD: ["Daredevil", "Jessica Jones", "Luke Cage", "Iron Fist", "Punisher", "Elektra", "Kingpin", "Bullseye", "Moon Knight", "Blade", "Ghost Rider", "Ms. Marvel", "She-Hulk", "Kate Bishop", "Yelena", "Red Guardian", "Taskmaster", "Agatha", "Monica Rambeau", "Sylvie", "Mobius", "Kang", "He Who Remains", "Ravonna", "Miss Minutes", "Alioth", "Watcher", "Infinity Ultron", "Zombie Hunter", "Captain Carter"],
      INSANE: ["Eternals", "Deviants", "Celestials", "Arishem", "Sersi", "Ikaris", "Thena", "Ajak", "Kingo", "Sprite", "Phastos", "Makkari", "Druig", "Gilgamesh", "Dane Whitman", "Eros", "Pip", "Starfox", "Black Knight", "Blade", "Morbius", "Kraven", "Chameleon", "Rhino", "Scorpion", "Shocker", "Vulture", "Mysterio", "Sandman", "Lizard"]
    }
  },
  {
    name: "DC",
    words: {
      EASY: ["Batman", "Superman", "Wonder Woman", "Flash", "Aquaman", "Cyborg", "Green Lantern", "Joker", "Harley Quinn", "Lex Luthor", "Catwoman", "Penguin", "Riddler", "Two-Face", "Bane", "Scarecrow", "Poison Ivy", "Mr. Freeze", "Robin", "Nightwing", "Batgirl", "Alfred", "Gordon", "Lois Lane", "Perry White", "Jimmy Olsen", "Zod", "Doomsday", "Darkseid", "Steppenwolf"],
      MEDIUM: ["Shazam", "Black Adam", "Hawkman", "Dr. Fate", "Atom Smasher", "Cyclone", "Blue Beetle", "Booster Gold", "Martian Manhunter", "Green Arrow", "Black Canary", "Supergirl", "Batwoman", "Red Hood", "Red Robin", "Spoiler", "Orphan", "Signal", "Huntress", "Power Girl", "Zatanna", "Constantine", "Swamp Thing", "Deadman", "Etrigan", "Raven", "Starfire", "Beast Boy", "Cyborg", "Robin"],
      HARD: ["Sinestro", "Atrocitus", "Larfleeze", "Saint Walker", "Indigo-1", "Star Sapphire", "Black Hand", "Nekron", "Parallax", "Ion", "Kilowog", "Tomar-Re", "Abin Sur", "Salaak", "Ch'p", "Mogo", "Ganthet", "Sayd", "Appa Ali Apsa", "Kronos", "Volthoom", "Relic", "Godhead", "Highfather", "Orion", "Mister Miracle", "Big Barda", "Granny Goodness", "Furies", "Kalibak"],
      INSANE: ["Spectre", "Phantom Stranger", "Question", "Pandora", "Anti-Monitor", "Monitor", "World Forger", "Perpetua", "Batman Who Laughs", "Owlman", "Ultraman", "Superwoman", "Power Ring", "Johnny Quick", "Sea King", "Grid", "Deathstorm", "Atomica", "Mazahs", "Relic", "Grail", "Myrina", "Metron", "Mobius", "Barbatos", "Upside-Down Man", "Empty Hand", "Gentry", "Overmonitor", "Presence"]
    }
  },
  {
    name: "Anime",
    words: {
      EASY: ["Goku", "Naruto", "Luffy", "Ichigo", "Sailor Moon", "Pikachu", "Totoro", "Spirited Away", "Pokemon", "Dragon Ball", "One Piece", "Bleach", "Naruto", "Attack on Titan", "Death Note", "Fullmetal Alchemist", "My Hero Academia", "Demon Slayer", "Jujutsu Kaisen", "One Punch Man", "Sword Art Online", "Tokyo Ghoul", "Hunter x Hunter", "Fairy Tail", "Black Clover", "JoJo", "Evangelion", "Gundam", "Cowboy Bebop", "Code Geass"],
      MEDIUM: ["Tanjiro", "Nezuko", "Zenitsu", "Inosuke", "Deku", "Bakugo", "Todoroki", "All Might", "Asta", "Yuno", "Noelle", "Yami", "Gon", "Killua", "Kurapika", "Leorio", "Eren", "Mikasa", "Armin", "Levi", "Light", "L", "Ryuk", "Misa", "Edward", "Alphonse", "Winry", "Roy", "Riza", "Hughes"],
      HARD: ["Guts", "Griffith", "Casca", "Kaneda", "Tetsuo", "Spike", "Jet", "Faye", "Ed", "Ein", "Shinji", "Asuka", "Rei", "Misato", "Gendo", "Lelouch", "Suzaku", "C.C.", "Kallen", "Nunnally", "Simon", "Kamina", "Yoko", "Nia", "Viral", "Ryuko", "Satsuki", "Mako", "Gamagori", "Sanageyama"],
      INSANE: ["Lain", "Kino", "Ginko", "D", "Vash", "Wolfwood", "Meryl", "Milly", "Knives", "Legato", "Gene", "Jim", "Melfina", "Aisha", "Suzuka", "Batou", "Togusa", "Ishikawa", "Saito", "Paz", "Borma", "Aramaki", "Motoko", "Kusanagi", "Tachikoma", "Logicoma", "Fuchikoma", "Uchikoma", "Havel", "Clarit"]
    }
  },
  {
    name: "Dog Breeds",
    words: {
      EASY: ["Poodle", "Bulldog", "Labrador", "Golden Retriever", "German Shepherd", "Beagle", "Boxer", "Dachshund", "Pug", "Husky", "Chihuahua", "Terrier", "Collie", "Dalmatian", "Rottweiler", "Doberman", "Shih Tzu", "Pomeranian", "Corgi", "Great Dane", "Mastiff", "Pitbull", "Greyhound", "Sheepdog", "Spaniel", "Setter", "Pointer", "Retriever", "Hound", "Bulldog"],
      MEDIUM: ["Malamute", "Samoyed", "Akita", "Shiba Inu", "Chow Chow", "Shar Pei", "Basenji", "Rhodesian Ridgeback", "Vizsla", "Weimaraner", "Bloodhound", "Basset Hound", "Coonhound", "Foxhound", "Harrier", "Whippet", "Saluki", "Borzoi", "Afghan Hound", "Irish Wolfhound", "Scottish Deerhound", "Otterhound", "Newfoundland", "St. Bernard", "Bernese Mountain Dog", "Great Pyrenees", "Kuvasz", "Komondor", "Puli", "Bergamasco"],
      HARD: ["Affenpinscher", "Brussels Griffon", "Cavalier King Charles", "English Toy Spaniel", "Havanese", "Italian Greyhound", "Japanese Chin", "Maltese", "Manchester Terrier", "Miniature Pinscher", "Papillon", "Pekingese", "Silky Terrier", "Toy Fox Terrier", "Yorkshire Terrier", "Bedlington Terrier", "Border Terrier", "Cairn Terrier", "Dandie Dinmont Terrier", "Glen of Imaal Terrier", "Irish Terrier", "Kerry Blue Terrier", "Lakeland Terrier", "Norfolk Terrier", "Norwich Terrier", "Parson Russell Terrier", "Rat Terrier", "Russell Terrier", "Scottish Terrier", "Sealyham Terrier"],
      INSANE: ["Skye Terrier", "Soft Coated Wheaten Terrier", "Staffordshire Bull Terrier", "Welsh Terrier", "West Highland White Terrier", "American Eskimo Dog", "Bichon Frise", "Boston Terrier", "Bulldog", "Chinese Shar-Pei", "Chow Chow", "Coton de Tulear", "Dalmatian", "Finnish Spitz", "French Bulldog", "Keeshond", "Lhasa Apso", "Lowchen", "Norwegian Lundehund", "Poodle", "Schipperke", "Shiba Inu", "Tibetan Spaniel", "Tibetan Terrier", "Xoloitzcuintli", "Australian Cattle Dog", "Australian Shepherd", "Bearded Collie", "Beauceron", "Belgian Malinois"]
    }
  },
  {
    name: "Insects",
    words: {
      EASY: ["Ant", "Bee", "Wasp", "Fly", "Mosquito", "Butterfly", "Moth", "Spider", "Scorpion", "Beetle", "Ladybug", "Cricket", "Grasshopper", "Cockroach", "Termite", "Flea", "Tick", "Louse", "Mite", "Worm", "Slug", "Snail", "Centipede", "Millipede", "Dragonfly", "Damselfly", "Mantis", "Stick Insect", "Leaf Insect", "Cicada"],
      MEDIUM: ["Aphid", "Weevil", "Stink Bug", "Bed Bug", "Assassin Bug", "Water Strider", "Backswimmer", "Water Boatman", "Giant Water Bug", "Scorpionfly", "Lacewing", "Antlion", "Dobsonfly", "Alderfly", "Snakefly", "Caddisfly", "Mayfly", "Stonefly", "Earwig", "Thrips", "Booklouse", "Barklouse", "Webspinner", "Zorapteran", "Grylloblattid", "Mantophasmatid", "Walkingstick", "Leaf Insect", "Katydid", "Cricket"],
      HARD: ["Silverfish", "Firebrat", "Springtail", "Bristletail", "Conehead", "Raspy Cricket", "Mole Cricket", "Camel Cricket", "Jerusalem Cricket", "Weta", "King Cricket", "Sand Groper", "Cooloola Monster", "Gladiator", "Heelwalker", "Stick Insect", "Leaf Insect", "Ghost Insect", "Angel Insect", "Violin Mantis", "Orchid Mantis", "Dead Leaf Mantis", "Flower Mantis", "Boxer Mantis", "Stick Mantis", "Bark Mantis", "Grass Mantis", "Ground Mantis", "Shield Mantis", "Cone Mantis"],
      INSANE: ["Protura", "Diplura", "Collembola", "Archaeognatha", "Zygentoma", "Ephemeroptera", "Odonata", "Plecoptera", "Embioptera", "Notoptera", "Dermaptera", "Mantodea", "Blattodea", "Isoptera", "Phasmatodea", "Orthoptera", "Psocoptera", "Phthiraptera", "Thysanoptera", "Hemiptera", "Neuroptera", "Megaloptera", "Raphidioptera", "Coleoptera", "Strepsiptera", "Mecoptera", "Siphonaptera", "Diptera", "Trichoptera", "Lepidoptera"]
    }
  },
  {
    name: "Phobias",
    words: {
      EASY: ["Spiders", "Snakes", "Heights", "Dark", "Flying", "Dogs", "Thunder", "Needles", "Germs", "Clowns", "Death", "Ghosts", "Aliens", "Monsters", "Blood", "Fire", "Water", "Drowning", "Choking", "Vomiting", "Pain", "Dentist", "Doctor", "Hospital", "School", "Work", "Failure", "Success", "Love", "Alone"],
      MEDIUM: ["Arachnophobia", "Ophidiophobia", "Acrophobia", "Agoraphobia", "Claustrophobia", "Cynophobia", "Astraphobia", "Trypanophobia", "Mysophobia", "Coulrophobia", "Thanatophobia", "Phasmophobia", "Xenophobia", "Terasophobia", "Hemophobia", "Pyrophobia", "Hydrophobia", "Aquaphobia", "Pnigophobia", "Emetophobia", "Algophobia", "Odontophobia", "Iatrophobia", "Nosocomephobia", "Scolionophobia", "Ergophobia", "Atychiphobia", "Achievemephobia", "Philophobia", "Monophobia"],
      HARD: ["Aerophobia", "Social Phobia", "Glossophobia", "Pathophobia", "Nyctophobia", "Necrophobia", "Erotophobia", "Gynophobia", "Androphobia", "Pedophobia", "Gerontophobia", "Xanthophobia", "Chromophobia", "Somniphobia", "Insomnia", "Hypnophobia", "Clinophobia", "Oneirophobia", "Chronophobia", "Gerascophobia", "Ephebiphobia", "Technophobia", "Cyberphobia", "Nomophobia", "Scopophobia", "Erythrophobia", "Gephyrophobia", "Hodophobia", "Aviophobia", "Siderodromophobia"],
      INSANE: ["Hippopotomonstrosesquippedaliophobia", "Hexakosioihexekontahexaphobia", "Triskaaidekaphobia", "Paraskevidekatriaphobia", "Anatidaephobia", "Arachibutyrophobia", "Nomophobia", "Omphalophobia", "Pogonophobia", "Trypophobia", "Turophobia", "Xanthophobia", "Zemmiphobia", "Alektorophobia", "Apiphobia", "Bufonophobia", "Equinophobia", "Galeophobia", "Herpetophobia", "Ichthyophobia", "Musophobia", "Ornithophobia", "Ostraconophobia", "Ranidaphobia", "Scoleciphobia", "Selachophobia", "Spheksophobia", "Taeniophobia", "Vermiphobia", "Zoophobia"]
    }
  },
  {
    name: "Holidays",
    words: {
      EASY: ["Christmas", "Halloween", "Easter", "Thanksgiving", "Valentine's Day", "New Year's Eve", "New Year's Day", "Birthday", "Mother's Day", "Father's Day", "Independence Day", "Labor Day", "Memorial Day", "Veterans Day", "Presidents' Day", "Martin Luther King Jr. Day", "Columbus Day", "St. Patrick's Day", "April Fool's Day", "Earth Day", "Flag Day", "Groundhog Day", "Hanukkah", "Kwanzaa", "Ramadan", "Diwali", "Chinese New Year", "Cinco de Mayo", "Bastille Day", "Oktoberfest"],
      MEDIUM: ["Boxing Day", "Epiphany", "Ash Wednesday", "Palm Sunday", "Good Friday", "Ascension Day", "Pentecost", "Trinity Sunday", "Corpus Christi", "Assumption", "All Saints' Day", "All Souls' Day", "Advent", "Christmas Eve", "New Year's Eve", "Twelfth Night", "Candlemas", "Shrove Tuesday", "Mardi Gras", "Lent", "Passover", "Rosh Hashanah", "Yom Kippur", "Sukkot", "Simchat Torah", "Purim", "Shavuot", "Tisha B'Av", "Lag BaOmer", "Tu BiShvat"],
      HARD: ["Eid al-Fitr", "Eid al-Adha", "Muharram", "Ashura", "Mawlid", "Isra and Mi'raj", "Laylat al-Qadr", "Holi", "Vaisakhi", "Raksha Bandhan", "Janmashtami", "Ganesh Chaturthi", "Navaratri", "Dussehra", "Onam", "Pongal", "Makar Sankranti", "Vasant Panchami", "Mahashivratri", "Rama Navami", "Hanuman Jayanti", "Guru Nanak Jayanti", "Lohri", "Baisakhi", "Karva Chauth", "Teej", "Chhath", "Bhai Dooj", "Govardhan Puja", "Dhanteras"],
      INSANE: ["Nowruz", "Yalda", "Chaharshanbe Suri", "Sizdah Bedar", "Tirgan", "Mehregan", "Sadeh", "Sepandarmazgan", "Zoroaster's Birthday", "Death of Zoroaster", "Mid-Autumn Festival", "Dragon Boat Festival", "Qingming Festival", "Double Ninth Festival", "Lantern Festival", "Hungry Ghost Festival", "Double Seventh Festival", "Laba Festival", "Spirit Festival", "Water Festival", "Songkran", "Thingyan", "Pi Mai", "Choul Chnam Thmey", "Bun Pi Mai", "Tet", "Seollal", "Chuseok", "Daeboreum", "Dano"]
    }
  },
  {
    name: "Spices",
    words: {
      EASY: ["Salt", "Pepper", "Sugar", "Cinnamon", "Garlic", "Onion", "Basil", "Oregano", "Parsley", "Rosemary", "Thyme", "Sage", "Mint", "Dill", "Ginger", "Nutmeg", "Clove", "Vanilla", "Chili", "Paprika", "Cumin", "Turmeric", "Curry", "Mustard", "Ketchup", "Mayo", "Vinegar", "Oil", "Butter", "Lemon"],
      MEDIUM: ["Allspice", "Anise", "Bay Leaf", "Caraway", "Cardamom", "Cayenne", "Celery Seed", "Chervil", "Chives", "Cilantro", "Coriander", "Fennel", "Fenugreek", "Horseradish", "Juniper", "Lavender", "Lemongrass", "Licorice", "Mace", "Marjoram", "Poppy Seed", "Saffron", "Savory", "Sesame", "Star Anise", "Tarragon", "Wasabi", "White Pepper", "Za'atar", "Sumac"],
      HARD: ["Ajwain", "Amchoor", "Asafoetida", "Barberry", "Black Cardamom", "Black Cumin", "Black Lime", "Black Salt", "Borage", "Cassia", "Charoli", "Cubeb", "Epazote", "Galangal", "Grains of Paradise", "Green Peppercorn", "Habanero", "Jalapeno", "Kaffir Lime", "Kokum", "Long Pepper", "Mahlab", "Mango Powder", "Nigella", "Pandan", "Pink Peppercorn", "Pomegranate", "Sansho", "Sichuan Pepper", "Tamarind"],
      INSANE: ["Advieh", "Baharat", "Berbere", "Bouquet Garni", "Cajun", "Chaat Masala", "Chili Powder", "Chinese Five Spice", "Curry Powder", "Dukkah", "Fines Herbes", "Garam Masala", "Gomashio", "Harissa", "Herbes de Provence", "Jerk", "Khmeli Suneli", "Lemon Pepper", "Old Bay", "Panch Phoron", "Pickling Spice", "Pumpkin Pie Spice", "Quatre Epices", "Ras el Hanout", "Sambar", "Shichimi Togarashi", "Tandoori", "Vadouvan", "Vindaloo", "Za'atar"]
    }
  },
  {
    name: "Dances",
    words: {
      EASY: ["Ballet", "Tap", "Jazz", "Hip Hop", "Salsa", "Tango", "Waltz", "Cha-Cha", "Rumba", "Samba", "Jive", "Swing", "Disco", "Breakdance", "Robot", "Moonwalk", "Macarena", "Twist", "Hokey Pokey", "Chicken Dance", "Conga", "Limbo", "Hula", "Belly Dance", "Polka", "Folk", "Square Dance", "Line Dance", "Slow Dance", "Freestyle"],
      MEDIUM: ["Foxtrot", "Quickstep", "Viennese Waltz", "Paso Doble", "Bolero", "Mambo", "Merengue", "Bachata", "Cumbia", "Reggaeton", "Dancehall", "Soca", "Calypso", "Zouk", "Kizomba", "Lambada", "Forro", "Capoeira", "Flamenco", "Fandango", "Sevillanas", "Jota", "Sardana", "Muneira", "Bolero", "Zarzuela", "Kathak", "Bharatanatyam", "Odissi", "Kuchipudi"],
      HARD: ["Kathakali", "Mohiniyattam", "Manipuri", "Sattriya", "Chhau", "Yakshagana", "Bhangra", "Giddha", "Garba", "Dandiya", "Lavani", "Tamasha", "Rouf", "Hikat", "Dumhal", "Kud", "Bhand Pather", "Hafiza", "Bacha Nagma", "Dhamali", "Chhakri", "Gojri", "Pahari", "Dogri", "Laddie", "Keekli", "Phumania", "Jhummar", "Luddi", "Sammi"],
      INSANE: ["Allemande", "Courante", "Sarabande", "Gigue", "Minuet", "Gavotte", "Bourree", "Passepied", "Rigaudon", "Loure", "Pavane", "Galliard", "Saltarello", "Canary", "Volta", "Tourdion", "Branle", "Morris", "Country", "Contra", "Ceili", "Step", "Highland", "Sword", "Reel", "Jig", "Strathspey", "Hornpipe", "Polka", "Mazurka"]
    }
  }
];

const UNDERCOVER_PRESETS: UndercoverCategory[] = [
  {
    name: "Food",
    pairs: {
      EASY: [["Apple", "Orange"], ["Banana", "Plantain"], ["Pizza", "Burger"], ["Coffee", "Tea"], ["Cake", "Pie"], ["Soup", "Stew"], ["Bread", "Toast"], ["Cookie", "Biscuit"], ["Chip", "Cracker"], ["Candy", "Chocolate"], ["Water", "Soda"], ["Milk", "Juice"], ["Chicken", "Turkey"], ["Beef", "Pork"], ["Salt", "Pepper"], ["Lemon", "Lime"], ["Peach", "Nectarine"], ["Grape", "Raisin"], ["Corn", "Peas"], ["Carrot", "Potato"], ["Rice", "Pasta"], ["Pancake", "Waffle"], ["Donut", "Bagel"], ["Yogurt", "Pudding"], ["Ice Cream", "Gelato"], ["Muffin", "Cupcake"], ["Butter", "Margarine"], ["Jam", "Jelly"], ["Ketchup", "Mustard"], ["Mayo", "Ranch"]],
      MEDIUM: [["Sushi", "Sashimi"], ["Taco", "Burrito"], ["Spaghetti", "Lasagna"], ["Omelette", "Scrambled Eggs"], ["Sausage", "Hot Dog"], ["Smoothie", "Milkshake"], ["Brownie", "Fudge"], ["Croissant", "Danish"], ["Baguette", "Sourdough"], ["Cheddar", "Mozzarella"], ["Almond", "Walnut"], ["Peanut", "Cashew"], ["Strawberry", "Raspberry"], ["Blueberry", "Blackberry"], ["Cucumber", "Zucchini"], ["Onion", "Shallot"], ["Garlic", "Ginger"], ["Basil", "Oregano"], ["Cinnamon", "Nutmeg"], ["Honey", "Syrup"], ["Guacamole", "Salsa"], ["Hummus", "Baba Ganoush"], ["Curry", "Stew"], ["Ramen", "Pho"], ["Tempura", "Fried Chicken"], ["Meatball", "Burger Patty"], ["Bacon", "Ham"], ["Steak", "Roast Beef"], ["Shrimp", "Prawn"], ["Salmon", "Tuna"]],
      HARD: [["Latte", "Cappuccino"], ["Macaron", "Macaroon"], ["Sorbet", "Sherbet"], ["Tortilla", "Flatbread"], ["Gyro", "Shawarma"], ["Prosciutto", "Pancetta"], ["Parmesan", "Pecorino"], ["Brie", "Camembert"], ["Gouda", "Edam"], ["Chorizo", "Salami"], ["Tofu", "Tempeh"], ["Quinoa", "Couscous"], ["Kale", "Spinach"], ["Arugula", "Lettuce"], ["Cilantro", "Parsley"], ["Rosemary", "Thyme"], ["Saffron", "Turmeric"], ["Cumin", "Coriander"], ["Paprika", "Chili Powder"], ["Wasabi", "Horseradish"], ["Miso", "Soy Sauce"], ["Kimchi", "Sauerkraut"], ["Pickle", "Relish"], ["Chutney", "Jam"], ["Pesto", "Chimichurri"], ["Gazpacho", "Salsa"], ["Chowder", "Bisque"], ["Risotto", "Paella"], ["Gnocchi", "Pasta"], ["Polenta", "Grits"]],
      INSANE: [["Cantaloupe", "Honeydew"], ["Tangerine", "Clementine"], ["Plantain", "Banana"], ["Sweet Potato", "Yam"], ["Scallion", "Chive"], ["Endive", "Radicchio"], ["Collard Greens", "Mustard Greens"], ["Swiss Chard", "Beet Greens"], ["Turnip", "Rutabaga"], ["Parsnip", "Carrot"], ["Currant", "Raisin"], ["Date", "Fig"], ["Prune", "Plum"], ["Apricot", "Peach"], ["Persimmon", "Tomato"], ["Durian", "Jackfruit"], ["Lychee", "Rambutan"], ["Papaya", "Mango"], ["Guava", "Passion Fruit"], ["Dragon Fruit", "Kiwi"], ["Star Anise", "Anise Seed"], ["Cardamom", "Clove"], ["Allspice", "Cinnamon"], ["Marjoram", "Oregano"], ["Sage", "Bay Leaf"], ["Tarragon", "Fennel"], ["Dill", "Fennel Fronds"], ["Caraway", "Cumin"], ["Sesame", "Poppy Seed"], ["Flax", "Chia"]]
    }
  },
  {
    name: "Animals",
    pairs: {
      EASY: [["Cat", "Dog"], ["Lion", "Tiger"], ["Horse", "Donkey"], ["Cow", "Pig"], ["Sheep", "Goat"], ["Duck", "Chicken"], ["Rabbit", "Hare"], ["Mouse", "Rat"], ["Frog", "Toad"], ["Snake", "Lizard"], ["Fish", "Shark"], ["Whale", "Dolphin"], ["Wolf", "Fox"], ["Bear", "Panda"], ["Monkey", "Gorilla"], ["Bee", "Wasp"], ["Ant", "Termite"], ["Fly", "Mosquito"], ["Butterfly", "Moth"], ["Spider", "Scorpion"], ["Crab", "Lobster"], ["Turtle", "Tortoise"], ["Eagle", "Hawk"], ["Owl", "Bat"], ["Penguin", "Puffin"], ["Seal", "Walrus"], ["Hippo", "Rhino"], ["Giraffe", "Zebra"], ["Deer", "Moose"], ["Squirrel", "Chipmunk"]],
      MEDIUM: [["Alligator", "Crocodile"], ["Leopard", "Cheetah"], ["Jaguar", "Panther"], ["Bison", "Buffalo"], ["Llama", "Alpaca"], ["Camel", "Dromedary"], ["Ostrich", "Emu"], ["Parrot", "Macaw"], ["Swan", "Goose"], ["Dove", "Pigeon"], ["Crow", "Raven"], ["Seagull", "Pelican"], ["Stork", "Heron"], ["Flamingo", "Crane"], ["Woodpecker", "Hummingbird"], ["Koala", "Wombat"], ["Kangaroo", "Wallaby"], ["Platypus", "Echidna"], ["Otter", "Beaver"], ["Racoon", "Badger"], ["Skunk", "Weasel"], ["Ferret", "Mongoose"], ["Hyena", "Jackal"], ["Coyote", "Dingo"], ["Husky", "Malamute"], ["Poodle", "Bichon"], ["Labrador", "Golden Retriever"], ["Siamese", "Persian"], ["Gecko", "Iguana"], ["Chameleon", "Salamander"]],
      HARD: [["Manatee", "Dugong"], ["Porpoise", "Dolphin"], ["Squid", "Octopus"], ["Jellyfish", "Man o' War"], ["Starfish", "Urchin"], ["Coral", "Sponge"], ["Shrimp", "Krill"], ["Barnacle", "Mussel"], ["Clam", "Oyster"], ["Snail", "Slug"], ["Centipede", "Millipede"], ["Beetle", "Ladybug"], ["Cricket", "Grasshopper"], ["Cicada", "Locust"], ["Dragonfly", "Damselfly"], ["Mantis", "Stick Insect"], ["Flea", "Louse"], ["Tick", "Mite"], ["Tarantula", "Widow"], ["Viper", "Cobra"], ["Python", "Boa"], ["Anaconda", "Boa Constrictor"], ["Monitor Lizard", "Komodo Dragon"], ["Newt", "Salamander"], ["Axolotl", "Mudpuppy"], ["Tapir", "Anteater"], ["Armadillo", "Pangolin"], ["Sloth", "Lemur"], ["Meerkat", "Prairie Dog"], ["Groundhog", "Gopher"]],
      INSANE: [["Bonobo", "Chimpanzee"], ["Baboon", "Mandrill"], ["Orangutan", "Gibbon"], ["Gorilla", "Sasquatch"], ["Lemur", "Bush Baby"], ["Loris", "Potto"], ["Tarsier", "Marmoset"], ["Tamarin", "Capuchin"], ["Howler Monkey", "Spider Monkey"], ["Macaque", "Langur"], ["Okapi", "Zebra"], ["Gazelle", "Impala"], ["Antelope", "Wildebeest"], ["Kudu", "Oryx"], ["Ibex", "Chamois"], ["Mouflon", "Argali"], ["Markhor", "Tahr"], ["Yak", "Muskox"], ["Caribou", "Reindeer"], ["Elk", "Wapiti"], ["Bobcat", "Lynx"], ["Cougar", "Puma"], ["Jaguarundi", "Ocelot"], ["Serval", "Caracal"], ["Fossa", "Civet"], ["Genet", "Linsang"], ["Binturong", "Kinkajou"], ["Coati", "Raccoon"], ["Mink", "Ermine"], ["Sable", "Marten"]]
    }
  },
  {
    name: "Objects",
    pairs: {
      EASY: [["Chair", "Stool"], ["Table", "Desk"], ["Sofa", "Bench"], ["Bed", "Cot"], ["Pillow", "Cushion"], ["Blanket", "Quilt"], ["Cup", "Mug"], ["Glass", "Bottle"], ["Plate", "Bowl"], ["Spoon", "Fork"], ["Knife", "Scissors"], ["Pen", "Pencil"], ["Book", "Notebook"], ["Phone", "Tablet"], ["Computer", "Laptop"], ["TV", "Monitor"], ["Keyboard", "Mouse"], ["Clock", "Watch"], ["Lamp", "Light"], ["Door", "Window"], ["Key", "Lock"], ["Bag", "Backpack"], ["Hat", "Cap"], ["Shoe", "Boot"], ["Sock", "Glove"], ["Shirt", "T-Shirt"], ["Pants", "Shorts"], ["Coat", "Jacket"], ["Ring", "Necklace"], ["Toothbrush", "Comb"]],
      MEDIUM: [["Broom", "Mop"], ["Bucket", "Bin"], ["Soap", "Shampoo"], ["Towel", "Rag"], ["Mirror", "Glass"], ["Candle", "Flashlight"], ["Battery", "Charger"], ["Wire", "Cable"], ["Remote", "Controller"], ["Speaker", "Headphone"], ["Camera", "Lens"], ["Photo", "Painting"], ["Frame", "Canvas"], ["Statue", "Figurine"], ["Vase", "Pot"], ["Flower", "Plant"], ["Tree", "Bush"], ["Grass", "Weed"], ["Fence", "Wall"], ["Gate", "Door"], ["Roof", "Ceiling"], ["Floor", "Ground"], ["Stairs", "Ladder"], ["Elevator", "Escalator"], ["Wheel", "Tire"], ["Engine", "Motor"], ["Pedal", "Handle"], ["Brake", "Gear"], ["Switch", "Button"], ["Knob", "Dial"]],
      HARD: [["Violin", "Viola"], ["Cello", "Bass"], ["Guitar", "Banjo"], ["Ukulele", "Mandolin"], ["Flute", "Piccolo"], ["Clarinet", "Oboe"], ["Trumpet", "Trombone"], ["Tuba", "Sousaphone"], ["Piano", "Organ"], ["Harp", "Lyre"], ["Drum", "Tambourine"], ["Cymbal", "Gong"], ["Maracas", "Shaker"], ["Xylophone", "Marimba"], ["Microphone", "Megaphone"], ["Telescope", "Microscope"], ["Binoculars", "Monocle"], ["Compass", "GPS"], ["Map", "Globe"], ["Ruler", "Tape Measure"], ["Thermometer", "Barometer"], ["Scale", "Balance"], ["Hammer", "Mallet"], ["Screwdriver", "Wrench"], ["Pliers", "Tweezers"], ["Saw", "Axe"], ["Drill", "Auger"], ["Nail", "Screw"], ["Bolt", "Nut"], ["Washer", "Gasket"]],
      INSANE: [["Blender", "Processor"], ["Mixer", "Whisk"], ["Toaster", "Oven"], ["Microwave", "Air Fryer"], ["Pot", "Pan"], ["Skillet", "Griddle"], ["Wok", "Cauldron"], ["Strainer", "Colander"], ["Spatula", "Ladle"], ["Tongs", "Pincers"], ["Grater", "Zester"], ["Peeler", "Corer"], ["Corkscrew", "Opener"], ["Funnel", "Siphon"], ["Pipette", "Dropper"], ["Beaker", "Flask"], ["Tube", "Cylinder"], ["Prism", "Lens"], ["Magnet", "Electromagnet"], ["Fuse", "Breaker"], ["Resistor", "Capacitor"], ["Diode", "Transistor"], ["Chip", "Processor"], ["Drive", "Disk"], ["Server", "Router"], ["Modem", "Switch"], ["Hub", "Repeater"], ["Cable", "Fiber"], ["Satellite", "Antenna"], ["Radar", "Sonar"]]
    }
  },
  {
    name: "Places",
    pairs: {
      EASY: [["House", "Apartment"], ["School", "College"], ["Store", "Shop"], ["Park", "Garden"], ["Beach", "Pool"], ["Forest", "Jungle"], ["Mountain", "Hill"], ["River", "Lake"], ["Ocean", "Sea"], ["City", "Town"], ["Village", "Farm"], ["Zoo", "Museum"], ["Cinema", "Theater"], ["Restaurant", "Cafe"], ["Hotel", "Motel"], ["Hospital", "Clinic"], ["Police Station", "Fire Station"], ["Bank", "Post Office"], ["Library", "Bookstore"], ["Gym", "Stadium"], ["Church", "Temple"], ["Mosque", "Synagogue"], ["Bridge", "Tunnel"], ["Road", "Street"], ["Path", "Trail"], ["Airport", "Station"], ["Bus Stop", "Train Station"], ["Port", "Harbor"], ["Island", "Peninsula"], ["Desert", "Canyon"]],
      MEDIUM: [["Kitchen", "Dining Room"], ["Living Room", "Bedroom"], ["Bathroom", "Toilet"], ["Attic", "Basement"], ["Garage", "Shed"], ["Porch", "Balcony"], ["Patio", "Deck"], ["Yard", "Lawn"], ["Fence", "Wall"], ["Roof", "Ceiling"], ["Office", "Studio"], ["Workshop", "Factory"], ["Warehouse", "Barn"], ["Silo", "Tower"], ["Castle", "Palace"], ["Fort", "Bunker"], ["Prison", "Jail"], ["Court", "Hall"], ["Arena", "Field"], ["Track", "Course"], ["Pool", "Pond"], ["Well", "Spring"], ["Canal", "Ditch"], ["Dam", "Levee"], ["Pier", "Dock"], ["Bay", "Gulf"], ["Cave", "Cavern"], ["Cliff", "Bluff"], ["Valley", "Gorge"], ["Dune", "Mound"]],
      HARD: [["Bakery", "Patisserie"], ["Butcher", "Deli"], ["Grocer", "Supermarket"], ["Market", "Bazaar"], ["Mall", "Plaza"], ["Boutique", "Outlet"], ["Salon", "Barber"], ["Spa", "Sauna"], ["Gym", "Dojo"], ["Rink", "Court"], ["Casino", "Arcade"], ["Club", "Bar"], ["Pub", "Tavern"], ["Diner", "Bistro"], ["Buffet", "Cafeteria"], ["Hostel", "Inn"], ["Lodge", "Cabin"], ["Resort", "Retreat"], ["Camp", "Site"], ["Park", "Reserve"], ["Sanctuary", "Refuge"], ["Zoo", "Aquarium"], ["Aviary", "Terrarium"], ["Greenhouse", "Nursery"], ["Orchard", "Vineyard"], ["Field", "Pasture"], ["Meadow", "Prairie"], ["Swamp", "Marsh"], ["Bog", "Fen"], ["Tundra", "Iceberg"]],
      INSANE: [["Capital", "Metropolis"], ["Suburb", "Outskirt"], ["District", "Zone"], ["Sector", "Ward"], ["County", "Province"], ["State", "Region"], ["Country", "Nation"], ["Continent", "Hemisphere"], ["Equator", "Pole"], ["Latitude", "Longitude"], ["Orbit", "Trajectory"], ["Space", "Void"], ["Galaxy", "Universe"], ["Star", "Sun"], ["Planet", "Moon"], ["Comet", "Asteroid"], ["Meteor", "Meteorite"], ["Nebula", "Supernova"], ["Black Hole", "Quasar"], ["Pulsar", "Magnetar"], ["Dimension", "Realm"], ["World", "Plane"], ["Nether", "Aether"], ["Heaven", "Hell"], ["Purgatory", "Limbo"], ["Utopia", "Dystopia"], ["Eden", "Paradise"], ["Oasis", "Mirage"], ["Dream", "Nightmare"], ["Reality", "Illusion"]]
    }
  },
  {
    name: "Activities",
    pairs: {
      EASY: [["Run", "Walk"], ["Jump", "Hop"], ["Swim", "Dive"], ["Fly", "Glide"], ["Drive", "Ride"], ["Eat", "Drink"], ["Sleep", "Nap"], ["Wake", "Rise"], ["Sit", "Stand"], ["Lie", "Lay"], ["Talk", "Speak"], ["Shout", "Scream"], ["Whisper", "Mumble"], ["Laugh", "Smile"], ["Cry", "Weep"], ["Read", "Write"], ["Draw", "Paint"], ["Sing", "Hum"], ["Dance", "Spin"], ["Play", "Work"], ["Cook", "Bake"], ["Clean", "Wash"], ["Buy", "Sell"], ["Give", "Take"], ["Push", "Pull"], ["Open", "Close"], ["Lock", "Unlock"], ["Start", "Stop"], ["Go", "Come"], ["Win", "Lose"]],
      MEDIUM: [["Jog", "Sprint"], ["Climb", "Hike"], ["Ski", "Snowboard"], ["Skate", "Rollerblade"], ["Surf", "Sail"], ["Row", "Paddle"], ["Fish", "Hunt"], ["Camp", "Picnic"], ["Travel", "Tour"], ["Visit", "Stay"], ["Watch", "Listen"], ["Hear", "See"], ["Touch", "Feel"], ["Smell", "Taste"], ["Think", "Dream"], ["Learn", "Study"], ["Teach", "Train"], ["Practice", "Rehearse"], ["Perform", "Act"], ["Direct", "Produce"], ["Build", "Create"], ["Make", "Fix"], ["Repair", "Mend"], ["Break", "Smash"], ["Cut", "Slice"], ["Chop", "Dice"], ["Mix", "Stir"], ["Boil", "Fry"], ["Grill", "Roast"], ["Toast", "Bake"]],
      HARD: [["Argue", "Debate"], ["Fight", "Battle"], ["Attack", "Defend"], ["Protect", "Guard"], ["Save", "Rescue"], ["Help", "Assist"], ["Serve", "Support"], ["Lead", "Guide"], ["Follow", "Chase"], ["Hunt", "Track"], ["Search", "Find"], ["Lose", "Miss"], ["Hide", "Seek"], ["Cover", "Reveal"], ["Show", "Display"], ["Hide", "Conceal"], ["Steal", "Rob"], ["Cheat", "Lie"], ["Trick", "Fool"], ["Joke", "Tease"], ["Laugh", "Giggle"], ["Smile", "Grin"], ["Frown", "Scowl"], ["Cry", "Sob"], ["Sigh", "Groan"], ["Yawn", "Sneeze"], ["Cough", "Choke"], ["Breathe", "Gasp"], ["Blink", "Wink"], ["Stare", "Glance"]],
      INSANE: [["Analyze", "Evaluate"], ["Assess", "Judge"], ["Criticize", "Review"], ["Comment", "Remark"], ["State", "Declare"], ["Announce", "Proclaim"], ["Ask", "Inquire"], ["Question", "Interrogate"], ["Answer", "Reply"], ["Respond", "React"], ["Ignore", "Neglect"], ["Avoid", "Evade"], ["Escape", "Flee"], ["Depart", "Leave"], ["Arrive", "Enter"], ["Exit", "Quit"], ["Resign", "Retire"], ["Hire", "Fire"], ["Promote", "Demote"], ["Employ", "Recruit"], ["Invest", "Spend"], ["Save", "Keep"], ["Earn", "Make"], ["Lose", "Waste"], ["Borrow", "Lend"], ["Owe", "Pay"], ["Buy", "Purchase"], ["Sell", "Trade"], ["Barter", "Swap"], ["Exchange", "Switch"]]
    }
  },
  {
    name: "Sports",
    pairs: {
      EASY: [["Soccer", "Rugby"], ["Basketball", "Netball"], ["Tennis", "Badminton"], ["Golf", "Mini Golf"], ["Swimming", "Diving"], ["Running", "Jogging"], ["Boxing", "Kickboxing"], ["Volleyball", "Handball"], ["Baseball", "Softball"], ["Football", "Soccer"], ["Hockey", "Ice Hockey"], ["Skiing", "Snowboarding"], ["Surfing", "Bodyboarding"], ["Skating", "Rollerblading"], ["Cycling", "Biking"], ["Gymnastics", "Acrobatics"], ["Wrestling", "Judo"], ["Karate", "Taekwondo"], ["Yoga", "Pilates"], ["Dance", "Ballet"], ["Cheer", "Dance"], ["Bowling", "Billiards"], ["Pool", "Snooker"], ["Darts", "Archery"], ["Cricket", "Baseball"], ["Table Tennis", "Ping Pong"], ["Squash", "Racquetball"], ["Lacrosse", "Hockey"], ["Figure Skating", "Speed Skating"], ["BMX", "Mountain Biking"]],
      MEDIUM: [["Fencing", "Kendo"], ["Archery", "Shooting"], ["Rowing", "Kayaking"], ["Canoeing", "Rafting"], ["Sailing", "Boating"], ["Equestrian", "Horse Racing"], ["Polo", "Water Polo"], ["Triathlon", "Decathlon"], ["Biathlon", "Pentathlon"], ["Bobsleigh", "Luge"], ["Skeleton", "Toboggan"], ["Curling", "Shuffleboard"], ["Climbing", "Bouldering"], ["Abseiling", "Rappelling"], ["Hiking", "Trekking"], ["Orienteering", "Geocaching"], ["Fishing", "Angling"], ["Hunting", "Trapping"], ["Paintball", "Airsoft"], ["Laser Tag", "Paintball"], ["Dodgeball", "Tag"], ["Ultimate", "Frisbee"], ["Parkour", "Freerunning"], ["Skateboarding", "Scootering"], ["Surfing", "Windsurfing"], ["Kitesurfing", "Wakeboarding"], ["Waterskiing", "Jet Skiing"], ["Snorkeling", "Scuba Diving"], ["Skydiving", "Paragliding"], ["Bungee Jumping", "Base Jumping"]],
      HARD: [["Sepak Takraw", "Volleyball"], ["Kabaddi", "Tag"], ["Hurling", "Hockey"], ["Gaelic Football", "Rugby"], ["Australian Rules", "Rugby"], ["Cricket", "Rounders"], ["Pesapallo", "Baseball"], ["Bandy", "Hockey"], ["Floorball", "Hockey"], ["Korfball", "Basketball"], ["Netball", "Basketball"], ["Futsal", "Soccer"], ["Beach Soccer", "Soccer"], ["Beach Volleyball", "Volleyball"], ["Water Polo", "Handball"], ["Tchoukball", "Handball"], ["Goalball", "Handball"], ["Wheelchair Rugby", "Rugby"], ["Wheelchair Basketball", "Basketball"], ["Sledge Hockey", "Hockey"], ["Sitting Volleyball", "Volleyball"], ["Boccia", "Bowls"], ["Petanque", "Boules"], ["Curling", "Bowls"], ["Shuffleboard", "Curling"], ["Croquet", "Golf"], ["Polo", "Croquet"], ["Lacrosse", "Hurling"], ["Shinty", "Hockey"], ["Camogie", "Hurling"]],
      INSANE: [["Chess Boxing", "Boxing"], ["Bossaball", "Volleyball"], ["Slamball", "Basketball"], ["Kronum", "Handball"], ["Quidditch", "Lacrosse"], ["Underwater Hockey", "Hockey"], ["Underwater Rugby", "Rugby"], ["Unicycle Hockey", "Hockey"], ["Cycle Ball", "Soccer"], ["Artistic Cycling", "Gymnastics"], ["Aerobatic Flying", "Gymnastics"], ["Wingsuit Flying", "Skydiving"], ["Free Diving", "Scuba Diving"], ["Ice Swimming", "Swimming"], ["Open Water Swimming", "Swimming"], ["Marathon Swimming", "Swimming"], ["Ultramarathon", "Marathon"], ["Skyrunning", "Trail Running"], ["Fell Running", "Cross Country"], ["Obstacle Course", "Parkour"], ["Adventure Racing", "Triathlon"], ["Swimrun", "Triathlon"], ["Aquathlon", "Triathlon"], ["Duathlon", "Triathlon"], ["Quadrathlon", "Triathlon"], ["Modern Pentathlon", "Pentathlon"], ["Military Pentathlon", "Pentathlon"], ["Naval Pentathlon", "Pentathlon"], ["Aeronautical Pentathlon", "Pentathlon"], ["Orienteering", "Navigation"]]
    }
  },
  {
    name: "Jobs",
    pairs: {
      EASY: [["Doctor", "Nurse"], ["Teacher", "Professor"], ["Police", "Guard"], ["Chef", "Cook"], ["Firefighter", "Paramedic"], ["Artist", "Painter"], ["Farmer", "Gardener"], ["Pilot", "Driver"], ["Singer", "Musician"], ["Actor", "Director"], ["Dancer", "Choreographer"], ["Writer", "Journalist"], ["Soldier", "Officer"], ["Judge", "Lawyer"], ["Baker", "Butcher"], ["Waiter", "Bartender"], ["Maid", "Janitor"], ["Coach", "Trainer"], ["Clerk", "Secretary"], ["Guide", "Scout"], ["Dentist", "Hygienist"], ["Vet", "Zoologist"], ["Mechanic", "Engineer"], ["Plumber", "Electrician"], ["Carpenter", "Builder"], ["Cleaner", "Washer"], ["Server", "Host"], ["Cashier", "Teller"], ["Manager", "Boss"], ["King", "Queen"]],
      MEDIUM: [["Architect", "Designer"], ["Scientist", "Researcher"], ["Journalist", "Reporter"], ["Surgeon", "Specialist"], ["Psychologist", "Psychiatrist"], ["Therapist", "Counselor"], ["Pharmacist", "Chemist"], ["Optometrist", "Ophthalmologist"], ["Chiropractor", "Physiotherapist"], ["Midwife", "Doula"], ["Librarian", "Archivist"], ["Curator", "Historian"], ["Translator", "Interpreter"], ["Diplomat", "Ambassador"], ["Politician", "Senator"], ["Mayor", "Governor"], ["President", "Prime Minister"], ["Captain", "Commander"], ["General", "Admiral"], ["Lieutenant", "Sergeant"], ["Detective", "Investigator"], ["Spy", "Agent"], ["Thief", "Burglar"], ["Assassin", "Hitman"], ["Sniper", "Marksman"], ["Bodyguard", "Bouncer"], ["Boxer", "Fighter"], ["Wrestler", "Grappler"], ["Athlete", "Player"], ["Coach", "Referee"]],
      HARD: [["Actuary", "Accountant"], ["Auditor", "Controller"], ["Analyst", "Strategist"], ["Consultant", "Advisor"], ["Broker", "Trader"], ["Banker", "Investor"], ["Economist", "Statistician"], ["Mathematician", "Physicist"], ["Chemist", "Biologist"], ["Geologist", "Geographer"], ["Astronomer", "Astrophysicist"], ["Meteorologist", "Climatologist"], ["Oceanographer", "Marine Biologist"], ["Ecologist", "Environmentalist"], ["Botanist", "Horticulturist"], ["Zoologist", "Veterinarian"], ["Geneticist", "Biotechnologist"], ["Microbiologist", "Immunologist"], ["Virologist", "Epidemiologist"], ["Pathologist", "Coroner"], ["Forensic Scientist", "Criminologist"], ["Toxicologist", "Pharmacologist"], ["Neurologist", "Neurosurgeon"], ["Cardiologist", "Surgeon"], ["Oncologist", "Radiologist"], ["Dermatologist", "Plastic Surgeon"], ["Pediatrician", "Obstetrician"], ["Geriatrician", "Internist"], ["Anesthesiologist", "Nurse Anesthetist"], ["Radiologist", "Technician"]],
      INSANE: [["Numismatist", "Philatelist"], ["Apiarist", "Beekeeper"], ["Horologist", "Watchmaker"], ["Vexillologist", "Herald"], ["Speleologist", "Spelunker"], ["Taxidermist", "Mortician"], ["Cooper", "Barrel Maker"], ["Cobbler", "Shoemaker"], ["Farrier", "Blacksmith"], ["Fletcher", "Bowyer"], ["Chandler", "Candle Maker"], ["Milliner", "Hatter"], ["Haberdasher", "Tailor"], ["Draper", "Clothier"], ["Mercer", "Merchant"], ["Scrivener", "Scribe"], ["Tanner", "Leatherworker"], ["Fuller", "Weaver"], ["Dyer", "Spinner"], ["Carder", "Comber"], ["Shearer", "Barber"], ["Thatcher", "Roofer"], ["Mason", "Bricklayer"], ["Wheelwright", "Wainwright"], ["Shipwright", "Boat Builder"], ["Cartwright", "Carriage Maker"], ["Arkwright", "Carpenter"], ["Ploughwright", "Farmer"], ["Sievewright", "Basket Maker"], ["Bridle Cutter", "Saddler"]]
    }
  },
  {
    name: "School",
    pairs: {
      EASY: [["Math", "Science"], ["English", "History"], ["Art", "Music"], ["Gym", "Recess"], ["Lunch", "Snack"], ["Pen", "Pencil"], ["Book", "Paper"], ["Desk", "Chair"], ["Teacher", "Principal"], ["Student", "Pupil"], ["Test", "Quiz"], ["Grade", "Score"], ["Class", "Room"], ["School", "College"], ["Bus", "Car"], ["Bag", "Pack"], ["Eraser", "Rubber"], ["Ruler", "Tape"], ["Glue", "Paste"], ["Scissors", "Cutter"], ["Marker", "Crayon"], ["Paint", "Brush"], ["Board", "Chalk"], ["Computer", "Tablet"], ["Phone", "Watch"], ["Clock", "Time"], ["Bell", "Ring"], ["Door", "Gate"], ["Friend", "Pal"], ["Game", "Play"]],
      MEDIUM: [["Algebra", "Geometry"], ["Biology", "Chemistry"], ["Physics", "Science"], ["Geography", "History"], ["Literature", "Reading"], ["Writing", "Grammar"], ["Spelling", "Vocabulary"], ["French", "Spanish"], ["German", "Italian"], ["Latin", "Greek"], ["Drama", "Theater"], ["Band", "Choir"], ["Orchestra", "Music"], ["Debate", "Speech"], ["Yearbook", "Newspaper"], ["Club", "Team"], ["Varsity", "Junior Varsity"], ["Captain", "Leader"], ["Coach", "Trainer"], ["Referee", "Umpire"], ["Library", "Lab"], ["Office", "Clinic"], ["Cafeteria", "Canteen"], ["Auditorium", "Gymnasium"], ["Stadium", "Field"], ["Track", "Court"], ["Pool", "Rink"], ["Locker", "Cubby"], ["Hallway", "Corridor"], ["Stairs", "Elevator"]],
      HARD: [["Calculus", "Trigonometry"], ["Statistics", "Probability"], ["Economics", "Finance"], ["Accounting", "Business"], ["Psychology", "Sociology"], ["Philosophy", "Ethics"], ["Logic", "Reasoning"], ["Anthropology", "Archaeology"], ["Political Science", "Government"], ["Civics", "Law"], ["Anatomy", "Physiology"], ["Botany", "Zoology"], ["Ecology", "Environmental Science"], ["Astronomy", "Geology"], ["Meteorology", "Oceanography"], ["Computer Science", "Coding"], ["Programming", "Engineering"], ["Architecture", "Design"], ["Graphic Design", "Art"], ["Photography", "Film"], ["Journalism", "Media"], ["Communication", "Speech"], ["Education", "Teaching"], ["Nursing", "Medicine"], ["Pharmacy", "Dentistry"], ["Veterinary", "Zoology"], ["Agriculture", "Farming"], ["Forestry", "Conservation"], ["Tourism", "Hospitality"], ["Culinary", "Cooking"]],
      INSANE: [["Thesis", "Dissertation"], ["Lecture", "Seminar"], ["Tutorial", "Workshop"], ["Symposium", "Conference"], ["Colloquium", "Forum"], ["Debate", "Panel"], ["Presentation", "Speech"], ["Essay", "Report"], ["Paper", "Article"], ["Journal", "Review"], ["Abstract", "Summary"], ["Introduction", "Conclusion"], ["Bibliography", "Reference"], ["Citation", "Quote"], ["Footnote", "Endnote"], ["Appendix", "Index"], ["Glossary", "Dictionary"], ["Thesaurus", "Encyclopedia"], ["Atlas", "Map"], ["Globe", "Chart"], ["Graph", "Table"], ["Diagram", "Figure"], ["Illustration", "Image"], ["Photo", "Picture"], ["Video", "Audio"], ["Recording", "Transcript"], ["Interview", "Survey"], ["Questionnaire", "Poll"], ["Study", "Experiment"], ["Research", "Analysis"]]
    }
  },
  {
    name: "Technology",
    pairs: {
      EASY: [["Phone", "Tablet"], ["Computer", "Laptop"], ["TV", "Radio"], ["Camera", "Video"], ["Game", "App"], ["Email", "Text"], ["Call", "Chat"], ["Music", "Sound"], ["Movie", "Show"], ["Pic", "Photo"], ["Web", "Net"], ["Site", "Page"], ["Link", "Click"], ["Mouse", "Touch"], ["Key", "Button"], ["Screen", "Display"], ["Power", "Battery"], ["Cord", "Wire"], ["Plug", "Jack"], ["Light", "Lamp"], ["Fan", "Air"], ["Heat", "Cold"], ["Clock", "Watch"], ["Alarm", "Timer"], ["Calc", "Math"], ["Map", "GPS"], ["Car", "Bus"], ["Train", "Plane"], ["Boat", "Ship"], ["Robot", "Machine"]],
      MEDIUM: [["iPhone", "Android"], ["Mac", "PC"], ["Windows", "Linux"], ["Chrome", "Firefox"], ["Google", "Bing"], ["Facebook", "Twitter"], ["Instagram", "TikTok"], ["Snapchat", "WhatsApp"], ["YouTube", "Netflix"], ["Hulu", "Disney+"], ["Amazon", "eBay"], ["Uber", "Lyft"], ["Airbnb", "Hotel"], ["Spotify", "Apple Music"], ["Kindle", "iPad"], ["Xbox", "PlayStation"], ["Nintendo", "Sega"], ["Mario", "Sonic"], ["Zelda", "Link"], ["Halo", "COD"], ["Fortnite", "Minecraft"], ["Roblox", "Lego"], ["Sims", "Animal Crossing"], ["Pokemon", "Digimon"], ["Magic", "Yu-Gi-Oh"], ["D&D", "Pathfinder"], ["Chess", "Checkers"], ["Poker", "Blackjack"], ["Solitaire", "Uno"], ["Go", "Baduk"]],
      HARD: [["Server", "Client"], ["Router", "Modem"], ["Switch", "Hub"], ["Firewall", "VPN"], ["Virus", "Malware"], ["Trojan", "Worm"], ["Spyware", "Adware"], ["Hacker", "Cracker"], ["Phishing", "Spam"], ["Bot", "Crawler"], ["Script", "Code"], ["Program", "App"], ["Software", "Hardware"], ["Memory", "Storage"], ["RAM", "ROM"], ["Disk", "Drive"], ["SSD", "HDD"], ["USB", "Thunderbolt"], ["HDMI", "VGA"], ["DVI", "DisplayPort"], ["Bluetooth", "WiFi"], ["NFC", "RFID"], ["GPS", "GLONASS"], ["LTE", "5G"], ["GSM", "CDMA"], ["SIM", "eSIM"], ["IP", "MAC"], ["DNS", "DHCP"], ["HTTP", "HTTPS"], ["FTP", "SSH"]],
      INSANE: [["Blockchain", "Crypto"], ["Bitcoin", "Ethereum"], ["NFT", "Token"], ["DeFi", "FinTech"], ["AI", "ML"], ["Neural Net", "Deep Learning"], ["Big Data", "Data Mining"], ["Cloud", "Edge"], ["SaaS", "PaaS"], ["IaaS", "Serverless"], ["Microservices", "Monolith"], ["Container", "VM"], ["Docker", "Kubernetes"], ["Git", "SVN"], ["Agile", "Scrum"], ["DevOps", "SysAdmin"], ["Frontend", "Backend"], ["Fullstack", "Mobile"], ["iOS", "Android"], ["Swift", "Kotlin"], ["Java", "C#"], ["Python", "Ruby"], ["JS", "TS"], ["HTML", "CSS"], ["React", "Vue"], ["Angular", "Svelte"], ["Node", "Deno"], ["SQL", "NoSQL"], ["REST", "GraphQL"], ["SOAP", "gRPC"]]
    }
  },
  {
    name: "Fantasy",
    pairs: {
      EASY: [["Dragon", "Dino"], ["Wizard", "Witch"], ["Elf", "Fairy"], ["Ghost", "Spirit"], ["Giant", "Troll"], ["King", "Queen"], ["Prince", "Princess"], ["Knight", "Warrior"], ["Sword", "Shield"], ["Bow", "Arrow"], ["Magic", "Power"], ["Spell", "Charm"], ["Potion", "Drink"], ["Wand", "Stick"], ["Castle", "Fort"], ["Tower", "Spire"], ["Dungeon", "Cave"], ["Monster", "Beast"], ["Hero", "Villain"], ["Good", "Evil"], ["Light", "Dark"], ["Sun", "Moon"], ["Star", "Sky"], ["Fire", "Ice"], ["Water", "Earth"], ["Air", "Wind"], ["Gold", "Silver"], ["Gem", "Jewel"], ["Ring", "Necklace"], ["Crown", "Hat"]],
      MEDIUM: [["Vampire", "Werewolf"], ["Zombie", "Skeleton"], ["Mummy", "Ghost"], ["Demon", "Devil"], ["Angel", "Spirit"], ["God", "Goddess"], ["Titan", "Giant"], ["Cyclops", "Ogre"], ["Goblin", "Orc"], ["Dwarf", "Gnome"], ["Halfling", "Hobbit"], ["Centaur", "Minotaur"], ["Satyr", "Faun"], ["Nymph", "Dryad"], ["Mermaid", "Siren"], ["Kraken", "Leviathan"], ["Hydra", "Dragon"], ["Phoenix", "Griffin"], ["Pegasus", "Unicorn"], ["Chimera", "Manticore"], ["Basilisk", "Cockatrice"], ["Gorgon", "Medusa"], ["Sphinx", "Riddle"], ["Genie", "Djinn"], ["Golem", "Construct"], ["Elemental", "Spirit"], ["Druid", "Shaman"], ["Cleric", "Priest"], ["Paladin", "Knight"], ["Rogue", "Thief"]],
      HARD: [["Sorcerer", "Warlock"], ["Mage", "Wizard"], ["Necromancer", "Lich"], ["Alchemist", "Artificer"], ["Bard", "Minstrel"], ["Ranger", "Hunter"], ["Monk", "Ninja"], ["Samurai", "Ronin"], ["Viking", "Barbarian"], ["Pirate", "Corsair"], ["Bandit", "Outlaw"], ["Assassin", "Spy"], ["Mercenary", "Soldier"], ["Guard", "Sentry"], ["Scout", "Spy"], ["Noble", "Royal"], ["Peasant", "Commoner"], ["Merchant", "Trader"], ["Smith", "Crafter"], ["Innkeeper", "Bartender"], ["Healer", "Doctor"], ["Sage", "Scholar"], ["Scribe", "Writer"], ["Oracle", "Prophet"], ["Seer", "Psychic"], ["Medium", "Channeler"], ["Exorcist", "Priest"], ["Inquisitor", "Judge"], ["Executioner", "Killer"], ["Jester", "Clown"]],
      INSANE: [["Amulet", "Talisman"], ["Relic", "Artifact"], ["Scroll", "Book"], ["Tome", "Grimoire"], ["Rune", "Symbol"], ["Sigil", "Mark"], ["Curse", "Hex"], ["Blessing", "Boon"], ["Enchantment", "Charm"], ["Illusion", "Mirage"], ["Summon", "Conjure"], ["Banish", "Exile"], ["Teleport", "Travel"], ["Fly", "Levitate"], ["Invisible", "Hidden"], ["Shape", "Shift"], ["Transform", "Change"], ["Polymorph", "Alter"], ["Petrify", "Freeze"], ["Paralyze", "Stun"], ["Silence", "Mute"], ["Blind", "Dazzle"], ["Deafen", "Muffle"], ["Poison", "Venom"], ["Disease", "Plague"], ["Fear", "Terror"], ["Charm", "Dominate"], ["Sleep", "Coma"], ["Death", "Doom"], ["Life", "Resurrect"]]
    }
  },
  {
    name: "Entertainment",
    pairs: {
      EASY: [["Movie", "Show"], ["Film", "Video"], ["Song", "Tune"], ["Music", "Sound"], ["Book", "Novel"], ["Game", "Play"], ["Toy", "Doll"], ["Art", "Draw"], ["Paint", "Color"], ["Dance", "Move"], ["Sing", "Hum"], ["Act", "Perform"], ["Funny", "Joke"], ["Sad", "Cry"], ["Happy", "Smile"], ["Scary", "Fear"], ["Love", "Kiss"], ["Hate", "Fight"], ["Win", "Lose"], ["Good", "Bad"], ["Hero", "Villain"], ["King", "Queen"], ["Prince", "Princess"], ["Boy", "Girl"], ["Man", "Woman"], ["Cat", "Dog"], ["Bird", "Fish"], ["Car", "Bus"], ["House", "Home"], ["School", "Work"]],
      MEDIUM: [["Comedy", "Drama"], ["Action", "Adventure"], ["Horror", "Thriller"], ["Sci-Fi", "Fantasy"], ["Romance", "Love"], ["Mystery", "Crime"], ["Documentary", "News"], ["Animation", "Cartoon"], ["Anime", "Manga"], ["Comic", "Graphic Novel"], ["Biograph", "Memoir"], ["History", "Fiction"], ["Poetry", "Prose"], ["Theater", "Cinema"], ["Concert", "Gig"], ["Festival", "Fair"], ["Museum", "Gallery"], ["Zoo", "Park"], ["Circus", "Carnival"], ["Magic", "Trick"], ["Puzzle", "Riddle"], ["Quiz", "Trivia"], ["Board Game", "Card Game"], ["Video Game", "Computer Game"], ["Console", "PC"], ["Mobile", "Tablet"], ["Stream", "Download"], ["Upload", "Share"], ["Like", "Follow"], ["Comment", "Review"]],
      HARD: [["Actor", "Actress"], ["Director", "Producer"], ["Writer", "Editor"], ["Cinematographer", "Photographer"], ["Composer", "Musician"], ["Singer", "Vocalist"], ["Band", "Group"], ["Orchestra", "Symphony"], ["Choir", "Chorus"], ["Dancer", "Choreographer"], ["Artist", "Painter"], ["Sculptor", "Architect"], ["Designer", "Stylist"], ["Model", "Celebrity"], ["Star", "Icon"], ["Influencer", "Blogger"], ["Vlogger", "Streamer"], ["Gamer", "Player"], ["Fan", "Follower"], ["Critic", "Reviewer"], ["Judge", "Jury"], ["Host", "Presenter"], ["Guest", "Visitor"], ["Audience", "Crowd"], ["Ticket", "Pass"], ["Seat", "Row"], ["Stage", "Screen"], ["Light", "Sound"], ["Prop", "Costume"], ["Makeup", "Hair"]],
      INSANE: [["Oscar", "Emmy"], ["Grammy", "Tony"], ["Golden Globe", "BAFTA"], ["Pulitzer", "Nobel"], ["MTV", "VH1"], ["HBO", "Showtime"], ["Netflix", "Hulu"], ["Amazon", "Disney"], ["Apple", "Google"], ["Sony", "Microsoft"], ["Nintendo", "Sega"], ["Marvel", "DC"], ["Star Wars", "Star Trek"], ["Harry Potter", "Lord of the Rings"], ["Game of Thrones", "Breaking Bad"], ["Friends", "Seinfeld"], ["Simpsons", "Family Guy"], ["SpongeBob", "Patrick"], ["Mickey", "Minnie"], ["Donald", "Goofy"], ["Batman", "Superman"], ["Spiderman", "Ironman"], ["Wonder Woman", "Captain Marvel"], ["Thor", "Hulk"], ["Joker", "Thanos"], ["Vader", "Voldemort"], ["Gandalf", "Dumbledore"], ["Sherlock", "Watson"], ["Bond", "Bourne"], ["Indy", "Han"]]
    }
  },
  {
    name: "Travel",
    pairs: {
      EASY: [["Car", "Bus"], ["Train", "Plane"], ["Boat", "Ship"], ["Bike", "Walk"], ["Drive", "Ride"], ["Fly", "Sail"], ["Go", "Stop"], ["Fast", "Slow"], ["Far", "Near"], ["Hot", "Cold"], ["Sun", "Rain"], ["Beach", "Pool"], ["Sand", "Dirt"], ["Water", "Land"], ["Tree", "Grass"], ["Hill", "Mountain"], ["River", "Lake"], ["Sea", "Ocean"], ["City", "Town"], ["Farm", "Zoo"], ["Park", "Shop"], ["Hotel", "House"], ["Bed", "Sleep"], ["Eat", "Food"], ["Drink", "Water"], ["Map", "Phone"], ["Bag", "Pack"], ["Ticket", "Pass"], ["Money", "Cash"], ["Card", "Coin"]],
      MEDIUM: [["Hotel", "Motel"], ["Hostel", "Inn"], ["Resort", "Spa"], ["Cabin", "Tent"], ["Camp", "Hike"], ["Swim", "Dive"], ["Surf", "Ski"], ["Snow", "Ice"], ["Desert", "Forest"], ["Jungle", "Safari"], ["Cruise", "Tour"], ["Guide", "Map"], ["Passport", "Visa"], ["Luggage", "Suitcase"], ["Backpack", "Carry-on"], ["Check-in", "Boarding"], ["Gate", "Terminal"], ["Airport", "Station"], ["Port", "Harbor"], ["Taxi", "Uber"], ["Subway", "Metro"], ["Tram", "Bus"], ["Train", "Rail"], ["Plane", "Jet"], ["Helicopter", "Drone"], ["Rocket", "Ship"], ["Space", "Moon"], ["Star", "Planet"], ["World", "Globe"], ["Earth", "Map"]],
      HARD: [["Tourist", "Traveler"], ["Visitor", "Guest"], ["Local", "Native"], ["Foreign", "Alien"], ["Language", "Speech"], ["Culture", "Custom"], ["Food", "Cuisine"], ["Drink", "Beverage"], ["Meal", "Snack"], ["Breakfast", "Lunch"], ["Dinner", "Supper"], ["Dessert", "Sweet"], ["Coffee", "Tea"], ["Beer", "Wine"], ["Water", "Soda"], ["Juice", "Milk"], ["Fruit", "Veggie"], ["Meat", "Fish"], ["Bread", "Rice"], ["Pasta", "Noodle"], ["Pizza", "Burger"], ["Soup", "Salad"], ["Sandwich", "Wrap"], ["Taco", "Burrito"], ["Sushi", "Sashimi"], ["Curry", "Stew"], ["Steak", "Chop"], ["Roast", "Grill"], ["Fry", "Boil"], ["Bake", "Cook"]],
      INSANE: [["London", "Paris"], ["Rome", "Milan"], ["Berlin", "Munich"], ["Madrid", "Barcelona"], ["Lisbon", "Porto"], ["Amsterdam", "Brussels"], ["Vienna", "Prague"], ["Budapest", "Warsaw"], ["Moscow", "Kiev"], ["Istanbul", "Athens"], ["Cairo", "Dubai"], ["Jerusalem", "Tel Aviv"], ["Mecca", "Medina"], ["Delhi", "Mumbai"], ["Beijing", "Shanghai"], ["Tokyo", "Osaka"], ["Seoul", "Busan"], ["Bangkok", "Hanoi"], ["Singapore", "KL"], ["Jakarta", "Bali"], ["Sydney", "Melbourne"], ["Auckland", "Wellington"], ["New York", "LA"], ["Chicago", "Houston"], ["Miami", "Orlando"], ["Toronto", "Vancouver"], ["Montreal", "Quebec"], ["Mexico City", "Cancun"], ["Rio", "Sao Paulo"], ["Buenos Aires", "Santiago"]]
    }
  },
  {
    name: "Body Parts",
    pairs: {
      EASY: [["Hand", "Foot"], ["Arm", "Leg"], ["Eye", "Ear"], ["Nose", "Mouth"], ["Head", "Face"], ["Hair", "Skin"], ["Finger", "Toe"], ["Thumb", "Pinky"], ["Knee", "Elbow"], ["Shoulder", "Hip"], ["Chest", "Back"], ["Stomach", "Belly"], ["Neck", "Throat"], ["Lip", "Tongue"], ["Tooth", "Gum"], ["Chin", "Cheek"], ["Forehead", "Brow"], ["Eyelash", "Lid"], ["Nail", "Claw"], ["Bone", "Muscle"], ["Blood", "Vein"], ["Heart", "Lung"], ["Brain", "Mind"], ["Skeleton", "Skull"], ["Ghost", "Spirit"], ["Man", "Woman"], ["Boy", "Girl"], ["Baby", "Child"], ["Old", "Young"], ["Tall", "Short"]],
      MEDIUM: [["Wrist", "Ankle"], ["Palm", "Sole"], ["Heel", "Arch"], ["Shin", "Calf"], ["Thigh", "Hamstring"], ["Bicep", "Tricep"], ["Forearm", "Upper Arm"], ["Knuckle", "Joint"], ["Spine", "Vertebra"], ["Rib", "Cage"], ["Pelvis", "Hips"], ["Collarbone", "Clavicle"], ["Shoulder Blade", "Scapula"], ["Breastbone", "Sternum"], ["Jaw", "Mandible"], ["Temple", "Side"], ["Pupil", "Iris"], ["Cornea", "Lens"], ["Retina", "Nerve"], ["Eardrum", "Canal"], ["Nostril", "Sinus"], ["Palate", "Roof"], ["Uvula", "Tonsil"], ["Larynx", "Voice Box"], ["Esophagus", "Tube"], ["Trachea", "Windpipe"], ["Bronchi", "Lungs"], ["Diaphragm", "Muscle"], ["Liver", "Kidney"], ["Stomach", "Intestine"]],
      HARD: [["Femur", "Thighbone"], ["Tibia", "Shinbone"], ["Fibula", "Calfbone"], ["Humerus", "Armbone"], ["Radius", "Ulna"], ["Carpal", "Wristbone"], ["Metacarpal", "Handbone"], ["Phalange", "Fingerbone"], ["Tarsal", "Anklebone"], ["Metatarsal", "Footbone"], ["Patella", "Kneecap"], ["Scapula", "Shoulder Blade"], ["Clavicle", "Collarbone"], ["Sternum", "Breastbone"], ["Rib", "Costal"], ["Vertebra", "Spine"], ["Sacrum", "Tailbone"], ["Coccyx", "Tailbone"], ["Pelvis", "Hipbone"], ["Ilium", "Hip"], ["Ischium", "Seat"], ["Pubis", "Front"], ["Skull", "Cranium"], ["Mandible", "Jawbone"], ["Maxilla", "Upper Jaw"], ["Zygomatic", "Cheekbone"], ["Nasal", "Nosebone"], ["Frontal", "Forehead"], ["Parietal", "Top"], ["Occipital", "Back"]],
      INSANE: [["Epidermis", "Dermis"], ["Hypodermis", "Fat"], ["Follicle", "Hair"], ["Gland", "Pore"], ["Sweat", "Oil"], ["Sebum", "Wax"], ["Keratin", "Protein"], ["Melanin", "Pigment"], ["Collagen", "Fiber"], ["Elastin", "Stretch"], ["Cartilage", "Gristle"], ["Ligament", "Band"], ["Tendon", "Cord"], ["Meniscus", "Pad"], ["Bursa", "Sac"], ["Synovium", "Lining"], ["Fluid", "Liquid"], ["Plasma", "Serum"], ["Cell", "Unit"], ["Nucleus", "Core"], ["DNA", "Code"], ["RNA", "Messenger"], ["Gene", "Trait"], ["Chromosome", "Strand"], ["Allele", "Variant"], ["Mutation", "Change"], ["Evolution", "Adaptation"], ["Species", "Type"], ["Genus", "Group"], ["Family", "Clan"]]
    }
  },
  {
    name: "Colors",
    pairs: {
      EASY: [["Red", "Pink"], ["Blue", "Green"], ["Yellow", "Orange"], ["Black", "White"], ["Gray", "Silver"], ["Gold", "Bronze"], ["Brown", "Tan"], ["Purple", "Violet"], ["Light", "Dark"], ["Bright", "Dull"], ["Clear", "Blurry"], ["Shiny", "Matte"], ["Hot", "Cold"], ["Warm", "Cool"], ["Soft", "Hard"], ["Smooth", "Rough"], ["Wet", "Dry"], ["Clean", "Dirty"], ["New", "Old"], ["Good", "Bad"], ["Happy", "Sad"], ["Love", "Hate"], ["Friend", "Enemy"], ["Boy", "Girl"], ["Man", "Woman"], ["Sun", "Moon"], ["Star", "Sky"], ["Fire", "Ice"], ["Water", "Earth"], ["Air", "Wind"]],
      MEDIUM: [["Crimson", "Scarlet"], ["Navy", "Royal"], ["Teal", "Turquoise"], ["Lime", "Olive"], ["Maroon", "Burgundy"], ["Magenta", "Fuchsia"], ["Cyan", "Aqua"], ["Indigo", "Violet"], ["Beige", "Cream"], ["Ivory", "White"], ["Charcoal", "Slate"], ["Jet", "Ebony"], ["Pearl", "Opal"], ["Ruby", "Garnet"], ["Sapphire", "Lapis"], ["Emerald", "Jade"], ["Topaz", "Amber"], ["Amethyst", "Lilac"], ["Lavender", "Periwinkle"], ["Peach", "Apricot"], ["Coral", "Salmon"], ["Rust", "Copper"], ["Brass", "Bronze"], ["Gold", "Platinum"], ["Silver", "Chrome"], ["Steel", "Iron"], ["Lead", "Tin"], ["Zinc", "Nickel"], ["Aluminum", "Titanium"], ["Uranium", "Plutonium"]],
      HARD: [["Vermilion", "Cinnabar"], ["Cerulean", "Azure"], ["Viridian", "Chartreuse"], ["Ochre", "Sienna"], ["Umber", "Sepia"], ["Taupe", "Khaki"], ["Mauve", "Plum"], ["Orchid", "Thistle"], ["Cornflower", "Sky"], ["Powder", "Baby"], ["Midnight", "Navy"], ["Forest", "Hunter"], ["Kelly", "Fern"], ["Mint", "Seafoam"], ["Pine", "Spruce"], ["Lemon", "Citron"], ["Canary", "Daffodil"], ["Mustard", "Gold"], ["Tangerine", "Mandarin"], ["Pumpkin", "Carrot"], ["Brick", "Tile"], ["Wine", "Grape"], ["Berry", "Cherry"], ["Rose", "Pink"], ["Blush", "Nude"], ["Skin", "Flesh"], ["Bone", "Skeleton"], ["Ash", "Dust"], ["Smoke", "Fog"], ["Mist", "Steam"]],
      INSANE: [["Heliotrope", "Lavender"], ["Amaranth", "Rose"], ["Coquelicot", "Red"], ["Smaragdine", "Emerald"], ["Glaucous", "Blue-Gray"], ["Wenge", "Brown"], ["Fulvous", "Yellow-Brown"], ["Xanadu", "Gray-Green"], ["Falu", "Red"], ["Eburnean", "Ivory"], ["Mikado", "Yellow"], ["Sarcoline", "Flesh"], ["Verdigris", "Green-Blue"], ["Zaffre", "Blue"], ["Gamboge", "Yellow"], ["Feldgrau", "Gray-Green"], ["Puce", "Purple-Brown"], ["Cordovan", "Red-Brown"], ["Bistre", "Brown"], ["Caput Mortuum", "Red-Brown"], ["Incarnadine", "Pink-Red"], ["Labrador", "Blue"], ["Isabelline", "Pale-Yellow"], ["Sinopia", "Red-Brown"], ["Titian", "Red-Gold"], ["Vanter", "Blue"], ["Watchet", "Blue"], ["Zomp", "Green"], ["Smalt", "Blue"], ["Sable", "Black"]]
    }
  },
  {
    name: "Transport",
    pairs: {
      EASY: [["Car", "Truck"], ["Bus", "Van"], ["Bike", "Scooter"], ["Skate", "Board"], ["Walk", "Run"], ["Train", "Tram"], ["Subway", "Metro"], ["Plane", "Jet"], ["Boat", "Ship"], ["Ferry", "Barge"], ["Taxi", "Cab"], ["Uber", "Lyft"], ["Limo", "Sedan"], ["Jeep", "SUV"], ["Convertible", "Coupe"], ["Wagon", "Hatchback"], ["Pickup", "Truck"], ["Semi", "Lorry"], ["Trailer", "Camper"], ["RV", "Motorhome"], ["Ambulance", "Police"], ["Fire", "Rescue"], ["Tractor", "Plow"], ["Crane", "Lift"], ["Dozer", "Digger"], ["Mixer", "Roller"], ["Tank", "Humvee"], ["Jet", "Rocket"], ["Shuttle", "Station"], ["UFO", "Alien"]],
      MEDIUM: [["Motorcycle", "Moped"], ["Bicycle", "Tricycle"], ["Unicycle", "Segway"], ["Hoverboard", "Scooter"], ["Skateboard", "Longboard"], ["Rollerblades", "Rollerskates"], ["Ice Skates", "Hockey Skates"], ["Ski", "Snowboard"], ["Sled", "Toboggan"], ["Kayak", "Canoe"], ["Raft", "Dinghy"], ["Yacht", "Sailboat"], ["Speedboat", "Motorboat"], ["Jet Ski", "Seadoo"], ["Submarine", "Submersible"], ["Ferry", "Catamaran"], ["Hovercraft", "Hydrofoil"], ["Glider", "Biplane"], ["Helicopter", "Chopper"], ["Blimp", "Zeppelin"], ["Balloon", "Dirigible"], ["Parachute", "Hang Glider"], ["Rocket", "Missile"], ["Satellite", "Probe"], ["Rover", "Lander"], ["Orbiter", "Capsule"], ["Station", "Base"], ["Colony", "Outpost"], ["Ship", "Fleet"], ["Armada", "Navy"]],
      HARD: [["Rickshaw", "Tuk-tuk"], ["Gondola", "Punt"], ["Sampan", "Junk"], ["Dhow", "Prau"], ["Catamaran", "Trimaran"], ["Sloop", "Ketch"], ["Schooner", "Brigantine"], ["Barque", "Clipper"], ["Galleon", "Frigate"], ["Corvette", "Destroyer"], ["Cruiser", "Battleship"], ["Carrier", "Dreadnought"], ["Sub", "U-boat"], ["Tanker", "Freighter"], ["Container", "Cargo"], ["Liner", "Cruise"], ["Tug", "Pilot"], ["Icebreaker", "Research"], ["Ferry", "Ro-Ro"], ["Barge", "Lighter"], ["Dredge", "Crane"], ["Rig", "Platform"], ["Drill", "Ship"], ["Supply", "Vessel"], ["Trawler", "Seiner"], ["Whaler", "Fisher"], ["Lifeboat", "Raft"], ["Dinghy", "Tender"], ["Launch", "Gig"], ["Skiff", "Dory"]],
      INSANE: [["Funicular", "Cable Car"], ["Monorail", "Maglev"], ["Bullet Train", "Shinkansen"], ["TGV", "ICE"], ["Eurostar", "Thalys"], ["Amtrak", "Via"], ["Greyhound", "Megabus"], ["Coach", "Bus"], ["Trolley", "Streetcar"], ["Tram", "Light Rail"], ["Subway", "Underground"], ["Tube", "Metro"], ["El", "SkyTrain"], ["People Mover", "Monorail"], ["Elevator", "Escalator"], ["Conveyor", "Belt"], ["Pipeline", "Tube"], ["Hyperloop", "Loop"], ["Teleporter", "Transporter"], ["Portal", "Gate"], ["Wormhole", "Jump"], ["Warp", "Drive"], ["Light", "Speed"], ["Time", "Machine"], ["TARDIS", "DeLorean"], ["Box", "Booth"], ["Phone", "Cell"], ["Wire", "Line"], ["Net", "Web"], ["Cloud", "Server"]]
    }
  },
  {
    name: "Music",
    pairs: {
      EASY: [["Pop", "Rock"], ["Rap", "Hip Hop"], ["Jazz", "Blues"], ["Country", "Folk"], ["Classical", "Opera"], ["Dance", "Techno"], ["Metal", "Punk"], ["Reggae", "Ska"], ["Soul", "R&B"], ["Funk", "Disco"], ["House", "Trance"], ["Dubstep", "Trap"], ["Indie", "Alt"], ["Emo", "Goth"], ["K-Pop", "J-Pop"], ["Latin", "Salsa"], ["Tango", "Cha-Cha"], ["Waltz", "Polka"], ["March", "Hymn"], ["Carol", "Song"], ["Tune", "Beat"], ["Rhythm", "Rhyme"], ["Verse", "Chorus"], ["Lyrics", "Words"], ["Note", "Key"], ["Chord", "Scale"], ["Band", "Group"], ["Solo", "Duet"], ["Trio", "Quartet"], ["Singer", "Player"]],
      MEDIUM: [["Guitar", "Bass"], ["Violin", "Cello"], ["Piano", "Organ"], ["Drum", "Percussion"], ["Flute", "Clarinet"], ["Trumpet", "Trombone"], ["Sax", "Horn"], ["Voice", "Vocals"], ["Mic", "Amp"], ["Speaker", "Headphones"], ["Record", "Vinyl"], ["CD", "Tape"], ["MP3", "Stream"], ["Radio", "Podcast"], ["Concert", "Festival"], ["Stage", "Studio"], ["Album", "Single"], ["EP", "LP"], ["Track", "Mix"], ["DJ", "Producer"], ["Composer", "Conductor"], ["Musician", "Artist"], ["Star", "Idol"], ["Fan", "Groupie"], ["Hit", "Flop"], ["Chart", "Top 40"], ["Award", "Prize"], ["Tour", "Show"], ["Ticket", "Pass"], ["Merch", "Gear"]],
      HARD: [["Soprano", "Alto"], ["Tenor", "Bass"], ["Baritone", "Mezzo"], ["Treble", "Clef"], ["Sharp", "Flat"], ["Major", "Minor"], ["Tempo", "Beat"], ["Time", "Signature"], ["Key", "Scale"], ["Chord", "Triad"], ["Arpeggio", "Riff"], ["Melody", "Harmony"], ["Rhythm", "Groove"], ["Syncopation", "Swing"], ["Improv", "Jam"], ["Solo", "Lead"], ["Backup", "Support"], ["Acoustic", "Electric"], ["Analog", "Digital"], ["Live", "Recorded"], ["Studio", "Demo"], ["Mix", "Master"], ["Remix", "Cover"], ["Sample", "Loop"], ["Synth", "Keyboard"], ["Drum Machine", "Sequencer"], ["Sampler", "DAW"], ["MIDI", "Audio"], ["Wave", "File"], ["Format", "Codec"]],
      INSANE: [["Allegro", "Presto"], ["Adagio", "Largo"], ["Andante", "Moderato"], ["Vivace", "Allegretto"], ["Grave", "Lento"], ["Forte", "Piano"], ["Crescendo", "Diminuendo"], ["Staccato", "Legato"], ["Pizzicato", "Arco"], ["Vibrato", "Tremolo"], ["Glissando", "Portamento"], ["Cadenza", "Coda"], ["Intro", "Outro"], ["Verse", "Bridge"], ["Chorus", "Hook"], ["Refrain", "Tag"], ["Break", "Drop"], ["Build", "Rise"], ["Fade", "Cut"], ["Loop", "Repeat"], ["Shuffle", "Random"], ["Playlist", "Queue"], ["Library", "Folder"], ["Genre", "Style"], ["Mood", "Vibe"], ["Feel", "Soul"], ["Heart", "Mind"], ["Spirit", "Body"], ["Life", "Death"], ["Love", "Hate"]]
    }
  },
  {
    name: "Weather",
    pairs: {
      EASY: [["Sun", "Moon"], ["Rain", "Snow"], ["Wind", "Cloud"], ["Hot", "Cold"], ["Wet", "Dry"], ["Storm", "Calm"], ["Day", "Night"], ["Light", "Dark"], ["Clear", "Fog"], ["Ice", "Fire"], ["Thunder", "Lightning"], ["Rainbow", "Sky"], ["Star", "Planet"], ["Earth", "Space"], ["World", "Globe"], ["Map", "Chart"], ["North", "South"], ["East", "West"], ["Up", "Down"], ["Left", "Right"], ["In", "Out"], ["On", "Off"], ["Open", "Close"], ["Start", "Stop"], ["Go", "Come"], ["Fast", "Slow"], ["Big", "Small"], ["High", "Low"], ["Long", "Short"], ["Fat", "Thin"]],
      MEDIUM: [["Hurricane", "Tornado"], ["Cyclone", "Typhoon"], ["Blizzard", "Storm"], ["Flood", "Drought"], ["Heatwave", "Cold Snap"], ["Frost", "Dew"], ["Mist", "Fog"], ["Hail", "Sleet"], ["Shower", "Drizzle"], ["Downpour", "Deluge"], ["Gale", "Breeze"], ["Gust", "Draft"], ["Humidity", "Dryness"], ["Pressure", "Temperature"], ["Forecast", "Report"], ["Radar", "Satellite"], ["Climate", "Weather"], ["Season", "Year"], ["Month", "Week"], ["Day", "Hour"], ["Minute", "Second"], ["Time", "Date"], ["Past", "Future"], ["Present", "Now"], ["History", "News"], ["Story", "Tale"], ["Fact", "Fiction"], ["Truth", "Lie"], ["Real", "Fake"], ["True", "False"]],
      HARD: [["Cumulus", "Stratus"], ["Cirrus", "Nimbus"], ["Altocumulus", "Altostratus"], ["Cirrocumulus", "Cirrostratus"], ["Nimbostratus", "Stratocumulus"], ["Mammatus", "Lenticular"], ["Contrail", "Cloud"], ["Aurora", "Borealis"], ["Australis", "Northern Lights"], ["Southern Lights", "Aurora"], ["Meteor", "Comet"], ["Asteroid", "Planetoid"], ["Galaxy", "Nebula"], ["Supernova", "Black Hole"], ["Quasar", "Pulsar"], ["Orbit", "Gravity"], ["Vacuum", "Space"], ["Atmosphere", "Ozone"], ["Layer", "Stratosphere"], ["Troposphere", "Mesosphere"], ["Thermosphere", "Exosphere"], ["Ionosphere", "Magnetosphere"], ["Crust", "Mantle"], ["Core", "Magma"], ["Lava", "Rock"], ["Stone", "Mineral"], ["Gem", "Crystal"], ["Diamond", "Gold"], ["Silver", "Bronze"], ["Iron", "Steel"]],
      INSANE: [["El Nino", "La Nina"], ["Monsoon", "Trade Wind"], ["Jet Stream", "Gulf Stream"], ["Vortex", "Eddy"], ["Front", "System"], ["High", "Low"], ["Ridge", "Trough"], ["Isobar", "Isotherm"], ["Gradient", "Slope"], ["Convergence", "Divergence"], ["Advection", "Convection"], ["Radiation", "Conduction"], ["Evaporation", "Condensation"], ["Precipitation", "Transpiration"], ["Sublimation", "Deposition"], ["Fusion", "Fission"], ["Entropy", "Energy"], ["Force", "Power"], ["Work", "Heat"], ["Light", "Sound"], ["Wave", "Particle"], ["Atom", "Molecule"], ["Electron", "Proton"], ["Neutron", "Quark"], ["String", "Theory"], ["Chaos", "Order"], ["Life", "Death"], ["Beginning", "End"], ["Alpha", "Omega"], ["First", "Last"]]
    }
  }
];

export const getPresetCategories = () => PRESETS.map(p => p.name).sort();

export const getUndercoverPresetCategories = () => UNDERCOVER_PRESETS.map(p => p.name).sort();

export const getRandomPreset = (difficulty: Difficulty, category?: string): { category: string, word: string } => {
  let availableCategories = PRESETS;
  
  if (category && category !== "Random") {
    availableCategories = PRESETS.filter(p => p.name === category);
  }

  if (availableCategories.length === 0) {
    availableCategories = PRESETS;
  }

  const randomCategory = availableCategories[Math.floor(Math.random() * availableCategories.length)];
  const words = randomCategory.words[difficulty] || randomCategory.words['MEDIUM'];
  const randomWord = words[Math.floor(Math.random() * words.length)];

  return {
    category: randomCategory.name,
    word: randomWord
  };
};

export const getRandomUndercoverPreset = (difficulty: Difficulty, category?: string): { category: string, secretWord: string, imposterWord: string } => {
  let availableCategories = UNDERCOVER_PRESETS;
  
  if (category && category !== "Random") {
    availableCategories = UNDERCOVER_PRESETS.filter(p => p.name === category);
  }

  if (availableCategories.length === 0) {
    availableCategories = UNDERCOVER_PRESETS;
  }

  const randomCategory = availableCategories[Math.floor(Math.random() * availableCategories.length)];
  const pairs = randomCategory.pairs[difficulty] || randomCategory.pairs['MEDIUM'];
  const randomPair = pairs[Math.floor(Math.random() * pairs.length)];

  // Randomly assign which word is secret vs imposter to add variety even with same pair
  const swap = Math.random() > 0.5;

  return {
    category: randomCategory.name,
    secretWord: swap ? randomPair[1] : randomPair[0],
    imposterWord: swap ? randomPair[0] : randomPair[1]
  };
};